# Import libraries

In [1]:
!pip install stargazer
!pip install altair
!pip install statsmodels

Looking in indexes: https://yzh79c:****@artifactory.gm.com/artifactory/api/pypi/python/simple
Collecting stargazer
  Using cached https://artifactory.gm.com/artifactory/api/pypi/python/packages/packages/28/32/fbd3d359cdc12dcdceb556bd40ab967878ad63b8a05445148ad1d2389573/stargazer-0.0.5-py3-none-any.whl
Installing collected packages: stargazer
Successfully installed stargazer-0.0.5
Looking in indexes: https://yzh79c:****@artifactory.gm.com/artifactory/api/pypi/python/simple
Collecting altair
  Using cached https://artifactory.gm.com/artifactory/api/pypi/python/packages/packages/01/55/0bb2226e34f21fa549c3f4557b4f154a5632f61132a969da17c95ca8eab9/altair-4.1.0-py3-none-any.whl
Requirement already satisfied: jinja2 in /opt/oss/conda3/lib/python3.7/site-packages (from altair) (2.10.1)
Requirement already satisfied: pandas>=0.18 in /opt/oss/conda3/lib/python3.7/site-packages (from altair) (0.25.0)
Requirement already satisfied: numpy in /opt/oss/conda3/lib/python3.7/site-packages (from altair) (1.16.2)
Requirement already satisfied: entrypoints in /opt/oss/conda3/lib/python3.7/site-packages (from altair) (0.3)
Requirement already satisfied: jsonschema in /opt/oss/conda3/lib/python3.7/site-packages (from altair) (3.0.2)
Collecting toolz (from altair)
  Using cached https://artifactory.gm.com/artifactory/api/pypi/python/packages/packages/12/f5/537e55f8ba664ff2a26f26913010fb0fcb98b6bbadc6158af888184fd0b7/toolz-0.11.1-py3-none-any.whl
Requirement already satisfied: MarkupSafe>=0.23 in /opt/oss/conda3/lib/python3.7/site-packages (from jinja2->altair) (1.1.1)
Requirement already satisfied: pytz>=2017.2 in /opt/oss/conda3/lib/python3.7/site-packages (from pandas>=0.18->altair) (2019.2)
Requirement already satisfied: python-dateutil>=2.6.1 in /opt/oss/conda3/lib/python3.7/site-packages (from pandas>=0.18->altair) (2.8.0)
Requirement already satisfied: pyrsistent>=0.14.0 in /opt/oss/conda3/lib/python3.7/site-packages (from jsonschema->altair) (0.15.4)
Requirement already satisfied: attrs>=17.4.0 in /opt/oss/conda3/lib/python3.7/site-packages (from jsonschema->altair) (19.1.0)
Requirement already satisfied: setuptools in /opt/oss/conda3/lib/python3.7/site-packages (from jsonschema->altair) (41.0.1)
Requirement already satisfied: six>=1.11.0 in /opt/oss/conda3/lib/python3.7/site-packages (from jsonschema->altair) (1.12.0)
Installing collected packages: toolz, altair
Successfully installed altair-4.1.0 toolz-0.11.1
Looking in indexes: https://yzh79c:****@artifactory.gm.com/artifactory/api/pypi/python/simple
Collecting statsmodels
  Using cached https://artifactory.gm.com/artifactory/api/pypi/python/packages/packages/da/69/8eef30a6237c54f3c0b524140e2975f4b1eea3489b45eb3339574fc8acee/statsmodels-0.12.2-cp37-cp37m-manylinux1_x86_64.whl
Collecting scipy>=1.1 (from statsmodels)
  Using cached https://artifactory.gm.com/artifactory/api/pypi/python/packages/packages/b5/6b/8bc0b61ebf824f8c3979a31368bbe38dd247590049a994ab0ed077cb56dc/scipy-1.7.1-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.whl
Collecting patsy>=0.5 (from statsmodels)
  Using cached https://artifactory.gm.com/artifactory/api/pypi/python/patsy/0.5.1/patsy-0.5.1-py2.py3-none-any.whl
Requirement already satisfied: numpy>=1.15 in /opt/oss/conda3/lib/python3.7/site-packages (from statsmodels) (1.16.2)
Requirement already satisfied: pandas>=0.21 in /opt/oss/conda3/lib/python3.7/site-packages (from statsmodels) (0.25.0)
Requirement already satisfied: six in /opt/oss/conda3/lib/python3.7/site-packages (from patsy>=0.5->statsmodels) (1.12.0)
Requirement already satisfied: pytz>=2017.2 in /opt/oss/conda3/lib/python3.7/site-packages (from pandas>=0.21->statsmodels) (2019.2)
Requirement already satisfied: python-dateutil>=2.6.1 in /opt/oss/conda3/lib/python3.7/site-packages (from pandas>=0.21->statsmodels) (2.8.0)
ERROR: scipy 1.7.1 has requirement numpy<1.23.0,>=1.16.5, but you'll have numpy 1.16.2 which is incompatible.
Installing collected packages: scipy, patsy, statsmodels
Successfully installed patsy-0.5.1 scipy-1.7.1 statsmodels-0.12.2

In [2]:
import pandas as pd
import numpy as np
import requests
import statsmodels.formula.api as smf
from stargazer.stargazer import Stargazer
import json
apikey = 'AU24y7aNaHPclqjxNcZkTA4q9HcNsVla2ILFhE7h'
import tqdm
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))
import datetime
import altair as alt

/opt/oss/conda3/lib/python3.7/site-packages/scipy/__init__.py:149: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.16.2
  UserWarning)

# Data extract

In [3]:
print('Started csv load @ ' + str(datetime.datetime.now()))

wash19incidents = pd.read_csv('washington/NIBRS_incident.csv')
wash19incidents['INCIDENT_MONTH'] = pd.DatetimeIndex(wash19incidents['INCIDENT_DATE']).month
wash19arrestees = pd.read_csv('washington/NIBRS_ARRESTEE.csv')
wash19offenseTypes = pd.read_csv('washington/NIBRS_OFFENSE_TYPE.csv')
relevant_offenses = ['Trespass of Real Property','Curfew/Loitering/Vagrancy Violations','Drug/Narcotic Violations','Drug Equipment Violations','Drunkenness','Disorderly Conduct','Family Offenses, Nonviolent']
wash19agencies = pd.read_csv('washington/agencies.csv')
wash19race = pd.read_csv('washington/REF_RACE.csv')
wash19justForce = pd.read_csv('washington/NIBRS_JUSTIFIABLE_FORCE.csv')
wash19victim = pd.read_csv('washington/NIBRS_VICTIM.csv')
wash19victimCirc = pd.read_csv('washington/NIBRS_VICTIM_CIRCUMSTANCES.csv')
wash19victimInj= pd.read_csv('washington/NIBRS_VICTIM_INJURY.csv')
wash19victimOffense = pd.read_csv('washington/NIBRS_VICTIM_OFFENSE.csv')
wash19victimType = pd.read_csv('washington/NIBRS_VICTIM_TYPE.csv')
wash19circCodes = pd.read_csv('washington/NIBRS_CIRCUMSTANCES.csv')
wash19injCodes = pd.read_csv('washington/NIBRS_INJURY.csv')

wash18incidents = pd.read_csv('washington/2018/NIBRS_incident.csv')
wash18incidents['INCIDENT_MONTH'] = pd.DatetimeIndex(wash18incidents['INCIDENT_DATE']).month
wash18arrestees = pd.read_csv('washington/2018/NIBRS_ARRESTEE.csv')
wash18offenseTypes = pd.read_csv('washington/2018/NIBRS_OFFENSE_TYPE.csv')
wash18agencies = pd.read_csv('washington/2018/agencies.csv')
wash18race = pd.read_csv('washington/2018/REF_RACE.csv')
wash18justForce = pd.read_csv('washington/2018/NIBRS_JUSTIFIABLE_FORCE.csv')
wash18victim = pd.read_csv('washington/2018/NIBRS_VICTIM.csv')
wash18victimCirc = pd.read_csv('washington/2018/NIBRS_VICTIM_CIRCUMSTANCES.csv')
wash18victimInj= pd.read_csv('washington/2018/NIBRS_VICTIM_INJURY.csv')
wash18victimOffense = pd.read_csv('washington/2018/NIBRS_VICTIM_OFFENSE.csv')
wash18victimType = pd.read_csv('washington/2018/NIBRS_VICTIM_TYPE.csv')
wash18circCodes = pd.read_csv('washington/2018/NIBRS_CIRCUMSTANCES.csv')
wash18injCodes = pd.read_csv('washington/NIBRS_INJURY.csv')

print('Finished csv load @ ' + str(datetime.datetime.now()))

Started csv load @ 2021-08-26 23:04:20.524341
Finished csv load @ 2021-08-26 23:05:28.833632

In [4]:
# display(wash19victimOffense)

In [5]:
wash19victim = wash19victim.merge(wash19victimCirc, how='left', on='VICTIM_ID')
wash19victim = wash19victim.merge(wash19circCodes, how='left', on='CIRCUMSTANCES_ID')
wash19victim = wash19victim.merge(wash19victimInj, how='left', on='VICTIM_ID')
wash19victim = wash19victim.merge(wash19victimType, how='left', on='VICTIM_TYPE_ID')
wash19victim = wash19victim.merge(wash19injCodes, how='left', on='INJURY_ID')
wash19victim = wash19victim.merge(wash19justForce, how='left', on='JUSTIFIABLE_FORCE_ID')
# wash19victim

In [6]:
wash18victim = wash18victim.merge(wash18victimCirc, how='left', on='VICTIM_ID')
wash18victim = wash18victim.merge(wash18circCodes, how='left', on='CIRCUMSTANCES_ID')
wash18victim = wash18victim.merge(wash18victimInj, how='left', on='VICTIM_ID')
wash18victim = wash18victim.merge(wash18victimType, how='left', on='VICTIM_TYPE_ID')
wash18victim = wash18victim.merge(wash18injCodes, how='left', on='INJURY_ID')
wash18victim = wash18victim.merge(wash18justForce, how='left', on='JUSTIFIABLE_FORCE_ID')
# wash18victim

In [7]:
print('Started merge @ ' + str(datetime.datetime.now()))

wash19offenses = pd.read_csv('washington/NIBRS_OFFENSE.csv')
wash19offenses = wash19offenses.merge(wash19incidents, how='left', on='INCIDENT_ID')
wash19offenses = wash19offenses.merge(wash19agencies, how='left', on='AGENCY_ID')
wash19offenses = wash19offenses.merge(wash19offenseTypes, how='left', on='OFFENSE_TYPE_ID')
wash19offenses = wash19offenses.merge(wash19arrestees, how='left', on='INCIDENT_ID')
wash19offenses = wash19offenses.merge(wash19race, how='left', on='RACE_ID')
wash19location = pd.read_csv('washington/NIBRS_LOCATION_TYPE.csv')
wash19offenses = wash19offenses.merge(wash19location, how='left', on='LOCATION_ID')
wash19offenses = wash19offenses.merge(wash19victim, how='left', on='INCIDENT_ID')


wash18offenses = pd.read_csv('washington/2018/NIBRS_OFFENSE.csv')
wash18offenses = wash18offenses.merge(wash18incidents, how='left', on='INCIDENT_ID')
wash18offenses = wash18offenses.merge(wash18agencies, how='left', on='AGENCY_ID')
wash18offenses = wash18offenses.merge(wash18offenseTypes, how='left', on='OFFENSE_TYPE_ID')
wash18offenses = wash18offenses.merge(wash18arrestees, how='left', on='INCIDENT_ID')
wash18offenses = wash18offenses.merge(wash18race, how='left', on='RACE_ID')
wash18location = pd.read_csv('washington/2018/NIBRS_LOCATION_TYPE.csv')
wash18offenses = wash18offenses.merge(wash18location, how='left', on='LOCATION_ID')
wash18offenses = wash18offenses.merge(wash18victim, how='left', on='INCIDENT_ID')

print('Finished merge @ ' + str(datetime.datetime.now()))

Started merge @ 2021-08-26 23:05:30.788764
Finished merge @ 2021-08-26 23:06:46.457424

In [8]:
#need to figure out which columns were added to arrestees dataframe and drop those from 18/19
wash1819offenses = pd.concat([wash19offenses,wash18offenses])
# wash1819offenses

In [9]:
olympia19offenses = wash19offenses[wash19offenses['COUNTY_NAME']=='THURSTON']
olympia19offenseCounts = pd.DataFrame(olympia19offenses.groupby(['INCIDENT_MONTH','OFFENSE_NAME'])['OFFENSE_NAME'].count())
pd.set_option('display.max_rows', 500)
olympia19offenseCounts = olympia19offenseCounts.rename(columns={'OFFENSE_NAME':'OFFENSE_COUNT'})
olympia19offenseCounts = olympia19offenseCounts.reset_index()
olympia19offenseCounts['CRU'] = np.where(olympia19offenseCounts['INCIDENT_MONTH']<4,0,1)
relevant_offenses = ['Trespass of Real Property','Curfew/Loitering/Vagrancy Violations','Drug/Narcotic Violations','Drug Equipment Violations','Drunkenness','Disorderly Conduct','Family Offenses, Nonviolent']
olympia19offenseCounts = olympia19offenseCounts[olympia19offenseCounts['OFFENSE_NAME'].isin(relevant_offenses)]
# olympia19offenseCounts = olympia19offenseCounts[olympia19offenseCounts['OFFENSE_NAME']=='Drug/Narcotic Violations']
# olympia19offenseCounts['Rolling'] = olympia19offenseCounts['OFFENSE_COUNT'].rolling(8).mean()

olympia1819offenses = wash1819offenses[wash1819offenses['COUNTY_NAME']=='THURSTON']
olympia1819offenses['INCIDENT_YEAR'] = pd.DatetimeIndex(olympia1819offenses['INCIDENT_DATE']).year
olympia1819offenseCounts = pd.DataFrame(olympia1819offenses.groupby(['INCIDENT_YEAR','INCIDENT_MONTH','OFFENSE_NAME'])['OFFENSE_NAME'].count())
pd.set_option('display.max_rows', 500)
olympia1819offenseCounts = olympia1819offenseCounts.rename(columns={'OFFENSE_NAME':'OFFENSE_COUNT'})
olympia1819offenseCounts = olympia1819offenseCounts.reset_index()
olympia1819offenseCounts['CRU'] = np.where((olympia1819offenseCounts['INCIDENT_MONTH']<4)|(olympia1819offenseCounts['INCIDENT_YEAR']==2018),0,1)
relevant_offenses = ['Trespass of Real Property','Curfew/Loitering/Vagrancy Violations','Drug/Narcotic Violations','Drug Equipment Violations','Drunkenness','Disorderly Conduct','Family Offenses, Nonviolent']
# olympia1819offenseCounts = olympia1819offenseCounts[olympia1819offenseCounts['OFFENSE_NAME'].isin(relevant_offenses)]
olympia1819offenseCounts = olympia1819offenseCounts[olympia1819offenseCounts['OFFENSE_NAME']=='Drug/Narcotic Violations']
# olympia19offenseCounts['Rolling'] = olympia19offenseCounts['OFFENSE_COUNT'].rolling(8).mean()

/opt/oss/conda3/lib/python3.7/site-packages/ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  del sys.path[0]

In [10]:
olympia19chart = alt.Chart(olympia19offenseCounts).mark_line().encode(
    x='INCIDENT_MONTH:O',
    y='OFFENSE_COUNT',
    color='OFFENSE_NAME'
)

In [11]:
olympia1819chart = alt.Chart(olympia1819offenseCounts,width=800, height=200).mark_line().encode(
    x='INCIDENT_MONTH:O',
    y='OFFENSE_COUNT',
    color=alt.Color('INCIDENT_YEAR:O',scale=alt.Scale(range=['#D15B41','#4B3D3D']))
)
display(olympia1819chart)
# olympia1819offenseCounts

alt.Chart(...)

In [12]:
olympia1819offenses = wash1819offenses[wash1819offenses['COUNTY_NAME']=='THURSTON']
olympia1819offenses['INCIDENT_YEAR'] = pd.DatetimeIndex(olympia1819offenses['INCIDENT_DATE']).year
#FILTER OUT INJURIES WE ARENT CONCERNED WITH
olympia1819injuryCounts = pd.DataFrame(olympia1819offenses.groupby(['INCIDENT_YEAR','INCIDENT_MONTH'])['INJURY_NAME'].count())
olympia1819injuryCounts = olympia1819injuryCounts.rename(columns={'INJURY_NAME':'INJURY_COUNT'})
olympia1819injuryCounts = olympia1819injuryCounts.reset_index()
olympia1819injuryCounts['CRU'] = np.where((olympia1819injuryCounts['INCIDENT_MONTH']<4)|(olympia1819injuryCounts['INCIDENT_YEAR']==2018),0,1)
olympia1819injuryCounts

/opt/oss/conda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

    INCIDENT_YEAR  INCIDENT_MONTH  INJURY_COUNT  CRU
0            2018               1           269    0
1            2018               2           255    0
2            2018               3           237    0
3            2018               4           262    0
4            2018               5           287    0
5            2018               6           265    0
6            2018               7           272    0
7            2018               8           242    0
8            2018               9           254    0
9            2018              10           249    0
10           2018              11           259    0
11           2018              12           277    0
12           2019               1           221    0
13           2019               2           203    0
14           2019               3           235    0
15           2019               4           244    1
16           2019               5           277    1
17           2019               6           255    1
18           2019               7           265    1
19           2019               8           256    1
20           2019               9           256    1
21           2019              10           222    1
22           2019              11           251    1
23           2019              12           267    1

In [13]:
olympia1819chart = alt.Chart(olympia1819injuryCounts,width=800, height=200).mark_line().encode(
    x='INCIDENT_MONTH:O',
    y='INJURY_COUNT',
    color=alt.Color('INCIDENT_YEAR:O',scale=alt.Scale(range=['#D15B41','#4B3D3D']))
)
display(olympia1819chart)

alt.Chart(...)

# Supervised models

## KNN classification

### Model development

### Visualization

### Analysis

## Logistic regression

### Model development

### Visualization

### Analysis

## Linear regression

### Model development

### Visualization

### Analysis

## OLS regression

### Model development

In [15]:
#RACE NORMALIZATION

olympia1819offenses = wash1819offenses[wash1819offenses['COUNTY_NAME']=='THURSTON']
olympia1819offenses['INCIDENT_YEAR'] = pd.DatetimeIndex(olympia1819offenses['INCIDENT_DATE']).year
olympia1819offenseCounts = pd.DataFrame(olympia1819offenses.groupby(['INCIDENT_YEAR','INCIDENT_MONTH','RACE_DESC'])['OFFENSE_NAME'].count())
olympia1819offenseCounts = olympia1819offenseCounts.rename(columns={'OFFENSE_NAME':'OFFENSE_COUNT'})
olympia1819offenseCounts = olympia1819offenseCounts.reset_index()
olympia1819offenseCounts['CRU'] = np.where((olympia1819offenseCounts['INCIDENT_MONTH']<4)|(olympia1819offenseCounts['INCIDENT_YEAR']==2018),0,1)
relevant_offenses = ['Trespass of Real Property','Curfew/Loitering/Vagrancy Violations','Drug/Narcotic Violations','Drug Equipment Violations','Drunkenness','Disorderly Conduct','Family Offenses, Nonviolent']
olympia1819offenseCounts = olympia1819offenseCounts[olympia1819offenseCounts.RACE_DESC != 'Unknown']
olympia1819offenseCountsRace = olympia1819offenseCounts[olympia1819offenseCounts['OFFENSE_COUNT'].isin(relevant_offenses)]


#Pull in CENSUS data

race_descriptions = olympia1819offenseCounts['RACE_DESC'].unique()

census_data_olympia = pd.read_csv('QuickFacts Aug-25-2021.csv')


race_descriptions_dict = {"White":75.9, "American Indian or Alaska Native":1.0, "Asian":7.1, "Black or African American": 2.6}


#Normalize Offense Rate
twenty_eighteen_total = olympia1819offenseCounts.groupby('INCIDENT_YEAR')['OFFENSE_COUNT'].sum()[2018]
twenty_nineteen_total = olympia1819offenseCounts.groupby('INCIDENT_YEAR')['OFFENSE_COUNT'].sum()[2019]
olympia1819offenseCounts['TOTAL_OFFENSES_PER_YEAR'] = np.where(olympia1819offenseCounts['INCIDENT_YEAR']==2018, twenty_eighteen_total, twenty_nineteen_total)
olympia1819offenseCounts['PCT_OF_POPULATION'] = olympia1819offenseCounts['RACE_DESC'].map(race_descriptions_dict)
olympia1819offenseCounts['WEIGHTED OFFENSE RATE'] = (100-olympia1819offenseCounts['PCT_OF_POPULATION']) * olympia1819offenseCounts['OFFENSE_COUNT']

/opt/oss/conda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.

In [73]:
#################################################################################################################################################

In [64]:
#####################
####Grouping data####
olympia1819offenses = wash1819offenses[wash1819offenses['COUNTY_NAME']=='THURSTON']
olympia1819offenses['INCIDENT_YEAR'] = pd.DatetimeIndex(olympia1819offenses['INCIDENT_DATE']).year
olympia1819offenseCounts = pd.DataFrame(olympia1819offenses.groupby(['INCIDENT_YEAR','INCIDENT_MONTH','RACE_DESC','OFFENSE_NAME'])['OFFENSE_NAME'].count())
olympia1819offenseCounts = olympia1819offenseCounts.rename(columns={'OFFENSE_NAME':'OFFENSE_COUNT'})
olympia1819offenseCounts = olympia1819offenseCounts.reset_index()
olympia1819offenseCounts['CRU'] = np.where((olympia1819offenseCounts['INCIDENT_MONTH']<4)|(olympia1819offenseCounts['INCIDENT_YEAR']==2018),0,1)
relevant_offenses = ['Trespass of Real Property','Curfew/Loitering/Vagrancy Violations','Drug/Narcotic Violations','Drug Equipment Violations','Drunkenness','Disorderly Conduct','Family Offenses, Nonviolent']
olympia1819offenseCountsRace = olympia1819offenseCounts[olympia1819offenseCounts['OFFENSE_NAME'].isin(relevant_offenses)]

modelA = smf.ols(formula='OFFENSE_COUNT ~ CRU', data=olympia1819offenseCountsRace).fit()
modelB = smf.ols(formula='OFFENSE_COUNT ~ CRU + RACE_DESC', data=olympia1819offenseCountsRace).fit()

olympia1819offenses = wash1819offenses[wash1819offenses['COUNTY_NAME']=='THURSTON']
olympia1819offenses['INCIDENT_YEAR'] = pd.DatetimeIndex(olympia1819offenses['INCIDENT_DATE']).year
olympia1819offenseCounts = pd.DataFrame(olympia1819offenses.groupby(['INCIDENT_YEAR','INCIDENT_MONTH','RACE_DESC','LOCATION_NAME','OFFENSE_NAME'])['OFFENSE_NAME'].count())
olympia1819offenseCounts = olympia1819offenseCounts.rename(columns={'OFFENSE_NAME':'OFFENSE_COUNT'})
olympia1819offenseCounts = olympia1819offenseCounts.reset_index()
olympia1819offenseCounts['CRU'] = np.where((olympia1819offenseCounts['INCIDENT_MONTH']<4)|(olympia1819offenseCounts['INCIDENT_YEAR']==2018),0,1)
relevant_offenses = ['Trespass of Real Property','Curfew/Loitering/Vagrancy Violations','Drug/Narcotic Violations','Drug Equipment Violations','Drunkenness','Disorderly Conduct','Family Offenses, Nonviolent']
olympia1819offenseCounts = olympia1819offenseCounts[olympia1819offenseCounts['OFFENSE_NAME'].isin(relevant_offenses)]

modelC = smf.ols(formula='OFFENSE_COUNT ~ CRU + RACE_DESC + LOCATION_NAME', data=olympia1819offenseCounts).fit()

### Example code ####

#`smf.ols(formula="y ~ treatment + x1 + x2 ...")#
#"fixed effect for var_x", you can add a `+C(var_x)`

#OFFENSE OLS REGRESSION#
########################
covariates = ['Intercept','CRU','RACE_DESC','LOCATION_NAME']
Q3_table = Stargazer([modelA,modelB,modelC])
# Q3_table.covariate_order(covariates)
Q3_table
#######################
#######################

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  app.launch_new_instance()

In [ ]:
#VICTIM OLS REGRESSION##
########################
covariates = ['Intercept','CRU','RACE_DESC','LOCATION_NAME','water_2006','apr_may_07']
modelA = smf.ols(formula='VICTIM_COUNT ~ CRU', data=a2).fit()
modelB = smf.ols(formula='VICTIM_COUNT ~ CRU + RACE_DESC +C(route)', data=a2).fit()
modelC = smf.ols(formula='VICTIM_COUNT ~ CRU + RACE_DESC + LOCATION_NAME +C(route)', data=a2).fit()
Q3_table = Stargazer([modelA,modelB,modelC])
Q3_table.covariate_order(covariates)
Q3_table
########################
########################

### Visualization

### Analysis

# Unsupervised models

## PCA

### Model development

### Visualization

### Analysis

## DBSCAN

### Model development

### Visualization

### Analysis

## API

In [2]:
### API call library ###
########################

# https://crime-data-explorer.fr.cloud.gov/pages/docApi

########################
########################

In [3]:
url = "https://api.usa.gov/crime/fbi/sapi/api/agencies/list?api_key=" + apikey
headers = {'Accept': 'application/json'}

response = requests.get(url, headers=headers)

data = json.loads(response.content)
agencies = pd.DataFrame(data)
oris = list(agencies['ori'].unique())

In [ ]:
#summarized-data-controller#
#second one - Agency level SRS crime data endpoint#
offenses = []
# for ori in tqdm(oris[:100]):
for ori in oris[:100]:
    try:
        url = f"https://api.usa.gov/crime/fbi/sapi/api/summarized/agencies/{ori}/offenses/2019/2021?api_key=" + apikey
        
        headers = {'Accept': 'application/json'}

        response = requests.get(url, headers=headers)

        data = json.loads(response.content)
        offenses.append(pd.DataFrame(data['results']))
    except:
        pass
    
offensesDf = pd.concat(offenses)
display(offensesDf)

In [14]:
url = f"https://api.usa.gov/crime/fbi/sapi/api/summarized/agencies/CODPD0000/offenses/2016/2018?api_key=" + apikey

headers = {'Accept': 'application/json'}

response = requests.get(url, headers=headers)

data = json.loads(response.content)
# pd.DataFrame(data['results'])

,ori,data_year,offense,state_abbr,cleared,actual,data_range
0,CODPD0000,2016,violent-crime,CO,2310,4602,None
1,CODPD0000,2016,robbery,CO,368,1159,None
2,CODPD0000,2016,motor-vehicle-theft,CO,588,4796,None
3,CODPD0000,2016,rape,CO,279,586,None
4,CODPD0000,2016,property-crime,CO,4259,25164,None
5,CODPD0000,2016,aggravated-assault,CO,1621,2801,None
6,CODPD0000,2016,human-trafficing,CO,0,0,None
7,CODPD0000,2016,arson,CO,25,94,None
8,CODPD0000,2016,burglary,CO,802,4681,None
9,CODPD0000,2016,rape-legacy,CO,0,0,None
10,CODPD0000,2016,homicide,CO,42,56,None
11,CODPD0000,2016,larceny,CO,2869,15687,None
12,CODPD0000,2017,motor-vehicle-theft,CO,637,5570,None
13,CODPD0000,2017,violent-crime,CO,2815,5338,None
14,CODPD0000,2017,robbery,CO,463,1232,None
15,CODPD0000,2017,rape-legacy,CO,232,514,None
16,CODPD0000,2017,rape,CO,374,746,None
17,CODPD0000,2017,property-crime,CO,3932,25995,None
18,CODPD0000,2017,larceny,CO,2638,16084,None
19,CODPD0000,2017,human-trafficing,CO,0,0,None
20,CODPD0000,2017,homicide,CO,39,57,None
21,CODPD0000,2017,burglary,CO,657,4341,None
22,CODPD0000,2017,arson,CO,37,132,None
23,CODPD0000,2017,aggravated-assault,CO,1707,2789,None
24,CODPD0000,2018,rape,CO,390,740,None
25,CODPD0000,2018,robbery,CO,437,1213,None
26,CODPD0000,2018,aggravated-assault,CO,2031,3277,None
27,CODPD0000,2018,arson,CO,24,117,None
28,CODPD0000,2018,burglary,CO,633,4021,None
29,CODPD0000,2018,homicide,CO,49,65,None
30,CODPD0000,2018,human-trafficing,CO,0,0,None
31,CODPD0000,2018,larceny,CO,2453,17391,None
32,CODPD0000,2018,motor-vehicle-theft,CO,695,5340,None
33,CODPD0000,2018,violent-crime,CO,3161,5824,None
34,CODPD0000,2018,property-crime,CO,3781,26752,None
35,CODPD0000,2018,rape-legacy,CO,254,529,None

In [16]:
#arrest-tkm-controller
offensesDemo = []
KC = 'MOKPD0000'
for ori in oris[:100]:
    try:
        url = f"https://api.usa.gov/crime/fbi/sapi/api/arrest/agencies/offense/{ori}/all/2018/2020?api_key=" + apikey
#         url = f"https://api.usa.gov/crime/fbi/sapi/api/arrest/agencies/offense/{KC}/drug/2019/2021?api_key=" + apikey
        headers = {'Accept': 'application/json'}

        response = requests.get(url, headers=headers)

        data = json.loads(response.content)
        display(data)
#         offensesDemo.append(pd.DataFrame(data['results']))
    except:
        pass
    
# offensesDemoDf = pd.concat(offensesDemo)

# url = f"https://api.usa.gov/crime/fbi/sapi/api/arrest/agencies/offense/{KC}/drug/2019/2021?api_key=" + apikey
# headers = {'Accept': 'application/json'}

# response = requests.get(url, headers=headers)

# data = json.loads(response.content)
# display(data)

# url = f"https://api.usa.gov/crime/fbi/sapi/api/arrest/agencies/{KC}/drug-grand-total/race/2019/2021?api_key=" + apikey
# headers = {'Accept': 'application/json'}

# response = requests.get(url, headers=headers)

# data = json.loads(response.content)
# display(data)

{'timestamp': '2021-08-14T15:47:55.477+00:00',
 'status': 500,
 'error': 'Internal Server Error',
 'message': '',
 'path': '/api/arrest/agencies/offense/AK0010100/all/2018/2020'}

{'timestamp': '2021-08-14T15:47:55.759+00:00',
 'status': 500,
 'error': 'Internal Server Error',
 'message': '',
 'path': '/api/arrest/agencies/offense/AK0010200/all/2018/2020'}

{'timestamp': '2021-08-14T15:47:56.072+00:00',
 'status': 500,
 'error': 'Internal Server Error',
 'message': '',
 'path': '/api/arrest/agencies/offense/AK0010300/all/2018/2020'}

{'timestamp': '2021-08-14T15:47:56.340+00:00',
 'status': 500,
 'error': 'Internal Server Error',
 'message': '',
 'path': '/api/arrest/agencies/offense/AK0010400/all/2018/2020'}

{'timestamp': '2021-08-14T15:47:56.636+00:00',
 'status': 500,
 'error': 'Internal Server Error',
 'message': '',
 'path': '/api/arrest/agencies/offense/AK0010500/all/2018/2020'}

{'timestamp': '2021-08-14T15:47:56.926+00:00',
 'status': 500,
 'error': 'Internal Server Error',
 'message': '',
 'path': '/api/arrest/agencies/offense/AK0010600/all/2018/2020'}

{'timestamp': '2021-08-14T15:47:57.224+00:00',
 'status': 500,
 'error': 'Internal Server Error',
 'message': '',
 'path': '/api/arrest/agencies/offense/AK0010700/all/2018/2020'}

{'timestamp': '2021-08-14T15:47:57.552+00:00',
 'status': 500,
 'error': 'Internal Server Error',
 'message': '',
 'path': '/api/arrest/agencies/offense/AK0010800/all/2018/2020'}

{'timestamp': '2021-08-14T15:47:57.841+00:00',
 'status': 500,
 'error': 'Internal Server Error',
 'message': '',
 'path': '/api/arrest/agencies/offense/AK0010900/all/2018/2020'}

{'timestamp': '2021-08-14T15:47:58.111+00:00',
 'status': 500,
 'error': 'Internal Server Error',
 'message': '',
 'path': '/api/arrest/agencies/offense/AK0011000/all/2018/2020'}

{'timestamp': '2021-08-14T15:47:58.417+00:00',
 'status': 500,
 'error': 'Internal Server Error',
 'message': '',
 'path': '/api/arrest/agencies/offense/AK0011100/all/2018/2020'}

{'timestamp': '2021-08-14T15:47:58.693+00:00',
 'status': 500,
 'error': 'Internal Server Error',
 'message': '',
 'path': '/api/arrest/agencies/offense/AK0011200/all/2018/2020'}

{'timestamp': '2021-08-14T15:47:58.992+00:00',
 'status': 500,
 'error': 'Internal Server Error',
 'message': '',
 'path': '/api/arrest/agencies/offense/AK0011300/all/2018/2020'}

{'timestamp': '2021-08-14T15:47:59.294+00:00',
 'status': 500,
 'error': 'Internal Server Error',
 'message': '',
 'path': '/api/arrest/agencies/offense/AK0011400/all/2018/2020'}

{'timestamp': '2021-08-14T15:47:59.569+00:00',
 'status': 500,
 'error': 'Internal Server Error',
 'message': '',
 'path': '/api/arrest/agencies/offense/AK0011600/all/2018/2020'}

{'timestamp': '2021-08-14T15:47:59.855+00:00',
 'status': 500,
 'error': 'Internal Server Error',
 'message': '',
 'path': '/api/arrest/agencies/offense/AK0011700/all/2018/2020'}

{'timestamp': '2021-08-14T15:48:00.141+00:00',
 'status': 500,
 'error': 'Internal Server Error',
 'message': '',
 'path': '/api/arrest/agencies/offense/AK0011800/all/2018/2020'}

{'timestamp': '2021-08-14T15:48:00.493+00:00',
 'status': 500,
 'error': 'Internal Server Error',
 'message': '',
 'path': '/api/arrest/agencies/offense/AK0011900/all/2018/2020'}

{'timestamp': '2021-08-14T15:48:00.804+00:00',
 'status': 500,
 'error': 'Internal Server Error',
 'message': '',
 'path': '/api/arrest/agencies/offense/AK0012000/all/2018/2020'}

{'timestamp': '2021-08-14T15:48:01.093+00:00',
 'status': 500,
 'error': 'Internal Server Error',
 'message': '',
 'path': '/api/arrest/agencies/offense/AK0012100/all/2018/2020'}

{'timestamp': '2021-08-14T15:48:01.380+00:00',
 'status': 500,
 'error': 'Internal Server Error',
 'message': '',
 'path': '/api/arrest/agencies/offense/AK0012200/all/2018/2020'}

{'timestamp': '2021-08-14T15:48:01.671+00:00',
 'status': 500,
 'error': 'Internal Server Error',
 'message': '',
 'path': '/api/arrest/agencies/offense/AK0012300/all/2018/2020'}

{'timestamp': '2021-08-14T15:48:01.958+00:00',
 'status': 500,
 'error': 'Internal Server Error',
 'message': '',
 'path': '/api/arrest/agencies/offense/AK0012500/all/2018/2020'}

{'timestamp': '2021-08-14T15:48:02.230+00:00',
 'status': 500,
 'error': 'Internal Server Error',
 'message': '',
 'path': '/api/arrest/agencies/offense/AK0012600/all/2018/2020'}

{'timestamp': '2021-08-14T15:48:02.511+00:00',
 'status': 500,
 'error': 'Internal Server Error',
 'message': '',
 'path': '/api/arrest/agencies/offense/AK0012700/all/2018/2020'}

{'timestamp': '2021-08-14T15:48:02.815+00:00',
 'status': 500,
 'error': 'Internal Server Error',
 'message': '',
 'path': '/api/arrest/agencies/offense/AK0012800/all/2018/2020'}

{'timestamp': '2021-08-14T15:48:03.115+00:00',
 'status': 500,
 'error': 'Internal Server Error',
 'message': '',
 'path': '/api/arrest/agencies/offense/AK0013000/all/2018/2020'}

{'timestamp': '2021-08-14T15:48:03.424+00:00',
 'status': 500,
 'error': 'Internal Server Error',
 'message': '',
 'path': '/api/arrest/agencies/offense/AK0013100/all/2018/2020'}

{'timestamp': '2021-08-14T15:48:03.719+00:00',
 'status': 500,
 'error': 'Internal Server Error',
 'message': '',
 'path': '/api/arrest/agencies/offense/AK0013200/all/2018/2020'}

{'timestamp': '2021-08-14T15:48:04.006+00:00',
 'status': 500,
 'error': 'Internal Server Error',
 'message': '',
 'path': '/api/arrest/agencies/offense/AK0013300/all/2018/2020'}

{'timestamp': '2021-08-14T15:48:04.308+00:00',
 'status': 500,
 'error': 'Internal Server Error',
 'message': '',
 'path': '/api/arrest/agencies/offense/AK0013500/all/2018/2020'}

{'timestamp': '2021-08-14T15:48:04.592+00:00',
 'status': 500,
 'error': 'Internal Server Error',
 'message': '',
 'path': '/api/arrest/agencies/offense/AK0014200/all/2018/2020'}

{'timestamp': '2021-08-14T15:48:04.930+00:00',
 'status': 500,
 'error': 'Internal Server Error',
 'message': '',
 'path': '/api/arrest/agencies/offense/AK0014300/all/2018/2020'}

{'timestamp': '2021-08-14T15:48:05.224+00:00',
 'status': 500,
 'error': 'Internal Server Error',
 'message': '',
 'path': '/api/arrest/agencies/offense/AK0014500/all/2018/2020'}

{'timestamp': '2021-08-14T15:48:05.518+00:00',
 'status': 500,
 'error': 'Internal Server Error',
 'message': '',
 'path': '/api/arrest/agencies/offense/AK0014600/all/2018/2020'}

{'timestamp': '2021-08-14T15:48:05.811+00:00',
 'status': 500,
 'error': 'Internal Server Error',
 'message': '',
 'path': '/api/arrest/agencies/offense/AK0015000/all/2018/2020'}

{'timestamp': '2021-08-14T15:48:06.094+00:00',
 'status': 500,
 'error': 'Internal Server Error',
 'message': '',
 'path': '/api/arrest/agencies/offense/AK0015200/all/2018/2020'}

{'timestamp': '2021-08-14T15:48:06.386+00:00',
 'status': 500,
 'error': 'Internal Server Error',
 'message': '',
 'path': '/api/arrest/agencies/offense/AK0015600/all/2018/2020'}

{'timestamp': '2021-08-14T15:48:06.688+00:00',
 'status': 500,
 'error': 'Internal Server Error',
 'message': '',
 'path': '/api/arrest/agencies/offense/AKAST0100/all/2018/2020'}

{'timestamp': '2021-08-14T15:48:07.004+00:00',
 'status': 500,
 'error': 'Internal Server Error',
 'message': '',
 'path': '/api/arrest/agencies/offense/AL0010000/all/2018/2020'}

{'timestamp': '2021-08-14T15:48:07.294+00:00',
 'status': 500,
 'error': 'Internal Server Error',
 'message': '',
 'path': '/api/arrest/agencies/offense/AL0010100/all/2018/2020'}

{'timestamp': '2021-08-14T15:48:07.576+00:00',
 'status': 500,
 'error': 'Internal Server Error',
 'message': '',
 'path': '/api/arrest/agencies/offense/AL0010200/all/2018/2020'}

{'timestamp': '2021-08-14T15:48:07.862+00:00',
 'status': 500,
 'error': 'Internal Server Error',
 'message': '',
 'path': '/api/arrest/agencies/offense/AL0010300/all/2018/2020'}

{'timestamp': '2021-08-14T15:48:08.166+00:00',
 'status': 500,
 'error': 'Internal Server Error',
 'message': '',
 'path': '/api/arrest/agencies/offense/AL0010400/all/2018/2020'}

{'timestamp': '2021-08-14T15:48:08.466+00:00',
 'status': 500,
 'error': 'Internal Server Error',
 'message': '',
 'path': '/api/arrest/agencies/offense/AL0010500/all/2018/2020'}

{'timestamp': '2021-08-14T15:48:08.776+00:00',
 'status': 500,
 'error': 'Internal Server Error',
 'message': '',
 'path': '/api/arrest/agencies/offense/AL0010600/all/2018/2020'}

{'timestamp': '2021-08-14T15:48:09.081+00:00',
 'status': 500,
 'error': 'Internal Server Error',
 'message': '',
 'path': '/api/arrest/agencies/offense/AL0010700/all/2018/2020'}

{'timestamp': '2021-08-14T15:48:09.386+00:00',
 'status': 500,
 'error': 'Internal Server Error',
 'message': '',
 'path': '/api/arrest/agencies/offense/AL0010800/all/2018/2020'}

{'timestamp': '2021-08-14T15:48:09.675+00:00',
 'status': 500,
 'error': 'Internal Server Error',
 'message': '',
 'path': '/api/arrest/agencies/offense/AL0010900/all/2018/2020'}

{'timestamp': '2021-08-14T15:48:09.975+00:00',
 'status': 500,
 'error': 'Internal Server Error',
 'message': '',
 'path': '/api/arrest/agencies/offense/AL0011000/all/2018/2020'}

{'timestamp': '2021-08-14T15:48:10.299+00:00',
 'status': 500,
 'error': 'Internal Server Error',
 'message': '',
 'path': '/api/arrest/agencies/offense/AL0011100/all/2018/2020'}

{'timestamp': '2021-08-14T15:48:10.600+00:00',
 'status': 500,
 'error': 'Internal Server Error',
 'message': '',
 'path': '/api/arrest/agencies/offense/AL0011200/all/2018/2020'}

{'timestamp': '2021-08-14T15:48:10.883+00:00',
 'status': 500,
 'error': 'Internal Server Error',
 'message': '',
 'path': '/api/arrest/agencies/offense/AL0011300/all/2018/2020'}

{'timestamp': '2021-08-14T15:48:11.163+00:00',
 'status': 500,
 'error': 'Internal Server Error',
 'message': '',
 'path': '/api/arrest/agencies/offense/AL0011400/all/2018/2020'}

{'timestamp': '2021-08-14T15:48:11.489+00:00',
 'status': 500,
 'error': 'Internal Server Error',
 'message': '',
 'path': '/api/arrest/agencies/offense/AL0011800/all/2018/2020'}

{'timestamp': '2021-08-14T15:48:11.774+00:00',
 'status': 500,
 'error': 'Internal Server Error',
 'message': '',
 'path': '/api/arrest/agencies/offense/AL0011900/all/2018/2020'}

{'timestamp': '2021-08-14T15:48:12.078+00:00',
 'status': 500,
 'error': 'Internal Server Error',
 'message': '',
 'path': '/api/arrest/agencies/offense/AL0012000/all/2018/2020'}

{'timestamp': '2021-08-14T15:48:12.375+00:00',
 'status': 500,
 'error': 'Internal Server Error',
 'message': '',
 'path': '/api/arrest/agencies/offense/AL0012100/all/2018/2020'}

{'timestamp': '2021-08-14T15:48:12.696+00:00',
 'status': 500,
 'error': 'Internal Server Error',
 'message': '',
 'path': '/api/arrest/agencies/offense/AL0012200/all/2018/2020'}

{'timestamp': '2021-08-14T15:48:13.023+00:00',
 'status': 500,
 'error': 'Internal Server Error',
 'message': '',
 'path': '/api/arrest/agencies/offense/AL0012300/all/2018/2020'}

{'timestamp': '2021-08-14T15:48:13.299+00:00',
 'status': 500,
 'error': 'Internal Server Error',
 'message': '',
 'path': '/api/arrest/agencies/offense/AL0012400/all/2018/2020'}

{'timestamp': '2021-08-14T15:48:13.592+00:00',
 'status': 500,
 'error': 'Internal Server Error',
 'message': '',
 'path': '/api/arrest/agencies/offense/AL0012500/all/2018/2020'}

{'timestamp': '2021-08-14T15:48:13.914+00:00',
 'status': 500,
 'error': 'Internal Server Error',
 'message': '',
 'path': '/api/arrest/agencies/offense/AL0012600/all/2018/2020'}

{'timestamp': '2021-08-14T15:48:14.216+00:00',
 'status': 500,
 'error': 'Internal Server Error',
 'message': '',
 'path': '/api/arrest/agencies/offense/AL0012700/all/2018/2020'}

{'timestamp': '2021-08-14T15:48:14.535+00:00',
 'status': 500,
 'error': 'Internal Server Error',
 'message': '',
 'path': '/api/arrest/agencies/offense/AL0012900/all/2018/2020'}

{'timestamp': '2021-08-14T15:48:14.832+00:00',
 'status': 500,
 'error': 'Internal Server Error',
 'message': '',
 'path': '/api/arrest/agencies/offense/AL0013200/all/2018/2020'}

{'timestamp': '2021-08-14T15:48:15.123+00:00',
 'status': 500,
 'error': 'Internal Server Error',
 'message': '',
 'path': '/api/arrest/agencies/offense/AL0013400/all/2018/2020'}

{'timestamp': '2021-08-14T15:48:15.416+00:00',
 'status': 500,
 'error': 'Internal Server Error',
 'message': '',
 'path': '/api/arrest/agencies/offense/AL001359E/all/2018/2020'}

{'timestamp': '2021-08-14T15:48:15.720+00:00',
 'status': 500,
 'error': 'Internal Server Error',
 'message': '',
 'path': '/api/arrest/agencies/offense/AL0014000/all/2018/2020'}

{'timestamp': '2021-08-14T15:48:16.016+00:00',
 'status': 500,
 'error': 'Internal Server Error',
 'message': '',
 'path': '/api/arrest/agencies/offense/AL001419E/all/2018/2020'}

{'timestamp': '2021-08-14T15:48:16.314+00:00',
 'status': 500,
 'error': 'Internal Server Error',
 'message': '',
 'path': '/api/arrest/agencies/offense/AL0014500/all/2018/2020'}

{'timestamp': '2021-08-14T15:48:16.591+00:00',
 'status': 500,
 'error': 'Internal Server Error',
 'message': '',
 'path': '/api/arrest/agencies/offense/AL0020000/all/2018/2020'}

{'timestamp': '2021-08-14T15:48:16.903+00:00',
 'status': 500,
 'error': 'Internal Server Error',
 'message': '',
 'path': '/api/arrest/agencies/offense/AL0020100/all/2018/2020'}

{'timestamp': '2021-08-14T15:48:17.178+00:00',
 'status': 500,
 'error': 'Internal Server Error',
 'message': '',
 'path': '/api/arrest/agencies/offense/AL0020200/all/2018/2020'}

{'timestamp': '2021-08-14T15:48:17.469+00:00',
 'status': 500,
 'error': 'Internal Server Error',
 'message': '',
 'path': '/api/arrest/agencies/offense/AL0020300/all/2018/2020'}

{'timestamp': '2021-08-14T15:48:17.773+00:00',
 'status': 500,
 'error': 'Internal Server Error',
 'message': '',
 'path': '/api/arrest/agencies/offense/AL0020400/all/2018/2020'}

{'timestamp': '2021-08-14T15:48:18.059+00:00',
 'status': 500,
 'error': 'Internal Server Error',
 'message': '',
 'path': '/api/arrest/agencies/offense/AL0020500/all/2018/2020'}

{'timestamp': '2021-08-14T15:48:18.371+00:00',
 'status': 500,
 'error': 'Internal Server Error',
 'message': '',
 'path': '/api/arrest/agencies/offense/AL0020600/all/2018/2020'}

{'timestamp': '2021-08-14T15:48:18.690+00:00',
 'status': 500,
 'error': 'Internal Server Error',
 'message': '',
 'path': '/api/arrest/agencies/offense/AL0020700/all/2018/2020'}

{'timestamp': '2021-08-14T15:48:19.003+00:00',
 'status': 500,
 'error': 'Internal Server Error',
 'message': '',
 'path': '/api/arrest/agencies/offense/AL0020800/all/2018/2020'}

{'timestamp': '2021-08-14T15:48:19.309+00:00',
 'status': 500,
 'error': 'Internal Server Error',
 'message': '',
 'path': '/api/arrest/agencies/offense/AL0021200/all/2018/2020'}

{'timestamp': '2021-08-14T15:48:19.631+00:00',
 'status': 500,
 'error': 'Internal Server Error',
 'message': '',
 'path': '/api/arrest/agencies/offense/AL0021300/all/2018/2020'}

{'timestamp': '2021-08-14T15:48:19.928+00:00',
 'status': 500,
 'error': 'Internal Server Error',
 'message': '',
 'path': '/api/arrest/agencies/offense/AL0021400/all/2018/2020'}

{'timestamp': '2021-08-14T15:48:20.218+00:00',
 'status': 500,
 'error': 'Internal Server Error',
 'message': '',
 'path': '/api/arrest/agencies/offense/AL0021500/all/2018/2020'}

{'timestamp': '2021-08-14T15:48:20.517+00:00',
 'status': 500,
 'error': 'Internal Server Error',
 'message': '',
 'path': '/api/arrest/agencies/offense/AL0021700/all/2018/2020'}

{'timestamp': '2021-08-14T15:48:20.803+00:00',
 'status': 500,
 'error': 'Internal Server Error',
 'message': '',
 'path': '/api/arrest/agencies/offense/AL0030000/all/2018/2020'}

{'timestamp': '2021-08-14T15:48:21.124+00:00',
 'status': 500,
 'error': 'Internal Server Error',
 'message': '',
 'path': '/api/arrest/agencies/offense/AL0030100/all/2018/2020'}

{'timestamp': '2021-08-14T15:48:21.409+00:00',
 'status': 500,
 'error': 'Internal Server Error',
 'message': '',
 'path': '/api/arrest/agencies/offense/AL0030500/all/2018/2020'}

{'timestamp': '2021-08-14T15:48:21.727+00:00',
 'status': 500,
 'error': 'Internal Server Error',
 'message': '',
 'path': '/api/arrest/agencies/offense/AL0030600/all/2018/2020'}

{'timestamp': '2021-08-14T15:48:22.006+00:00',
 'status': 500,
 'error': 'Internal Server Error',
 'message': '',
 'path': '/api/arrest/agencies/offense/AL0030700/all/2018/2020'}

{'timestamp': '2021-08-14T15:48:22.309+00:00',
 'status': 500,
 'error': 'Internal Server Error',
 'message': '',
 'path': '/api/arrest/agencies/offense/AL0030800/all/2018/2020'}

{'timestamp': '2021-08-14T15:48:22.592+00:00',
 'status': 500,
 'error': 'Internal Server Error',
 'message': '',
 'path': '/api/arrest/agencies/offense/AL0031400/all/2018/2020'}

{'timestamp': '2021-08-14T15:48:22.898+00:00',
 'status': 500,
 'error': 'Internal Server Error',
 'message': '',
 'path': '/api/arrest/agencies/offense/AL0033200/all/2018/2020'}

{'timestamp': '2021-08-14T15:48:23.197+00:00',
 'status': 500,
 'error': 'Internal Server Error',
 'message': '',
 'path': '/api/arrest/agencies/offense/AL0040000/all/2018/2020'}

{'timestamp': '2021-08-14T15:48:23.477+00:00',
 'status': 500,
 'error': 'Internal Server Error',
 'message': '',
 'path': '/api/arrest/agencies/offense/AL0040100/all/2018/2020'}

{'timestamp': '2021-08-14T15:48:23.756+00:00',
 'status': 500,
 'error': 'Internal Server Error',
 'message': '',
 'path': '/api/arrest/agencies/offense/AL0040200/all/2018/2020'}

{'timestamp': '2021-08-14T15:48:24.090+00:00',
 'status': 500,
 'error': 'Internal Server Error',
 'message': '',
 'path': '/api/arrest/agencies/offense/AL0050000/all/2018/2020'}

{'timestamp': '2021-08-14T15:48:24.387+00:00',
 'status': 500,
 'error': 'Internal Server Error',
 'message': '',
 'path': '/api/arrest/agencies/offense/AL0050100/all/2018/2020'}

{'timestamp': '2021-08-14T15:48:24.711+00:00',
 'status': 500,
 'error': 'Internal Server Error',
 'message': '',
 'path': '/api/arrest/agencies/offense/AL0050200/all/2018/2020'}

{'timestamp': '2021-08-14T15:48:25.000+00:00',
 'status': 500,
 'error': 'Internal Server Error',
 'message': '',
 'path': '/api/arrest/agencies/offense/AL0050300/all/2018/2020'}

In [16]:
agencies = requests.get('https://api.usa.gov/crime/fbi/sapi/api/nibrs/property-crime',auth=('key',apikey))
data = json.loads(agencies.content)
# pd.DataFrame(data)
data

{'error': {'code': 'API_KEY_INVALID',
  'message': 'An invalid api_key was supplied. Get one at https://api.usa.gov:443'}}