In [1]:
import pandas as pd
import numpy as np
import altair as alt

In [2]:
MO2019Offenses = pd.read_csv('NIBRS_OFFENSE.csv')
# MO2018Offenses = pd.read_csv('')

In [3]:
MO2019Offenses

,DATA_YEAR,OFFENSE_ID,INCIDENT_ID,OFFENSE_TYPE_ID,ATTEMPT_COMPLETE_FLAG,LOCATION_ID,NUM_PREMISES_ENTERED,METHOD_ENTRY_CODE
0,2019,133892120,109265381,45,C,7,NaN,NaN
1,2019,133892125,109259840,16,C,13,NaN,NaN
2,2019,133887750,109266759,41,C,47,NaN,NaN
3,2019,133887762,109265397,35,C,12,NaN,NaN
4,2019,133882715,109259897,21,C,20,NaN,NaN
...,...,...,...,...,...,...,...,...
126105,2019,148794439,122990247,5,C,20,NaN,NaN
126106,2019,148794458,122990264,45,C,23,NaN,NaN
126107,2019,148790736,122990275,51,C,20,NaN,NaN
126108,2019,148794501,122985921,23,C,8,NaN,NaN
126109,2019,148790779,122990323,49,C,20,NaN,N

In [4]:
Arrestees = pd.read_csv('NIBRS_ARRESTEE.csv')

In [5]:
Arrestees

,DATA_YEAR,ARRESTEE_ID,INCIDENT_ID,ARRESTEE_SEQ_NUM,ARREST_DATE,ARREST_TYPE_ID,MULTIPLE_INDICATOR,OFFENSE_TYPE_ID,AGE_ID,AGE_NUM,SEX_CODE,RACE_ID,ETHNICITY_ID,RESIDENT_CODE,UNDER_18_DISPOSITION_CODE,CLEARANCE_IND,AGE_RANGE_LOW_NUM,AGE_RANGE_HIGH_NUM
0,2019,37347156,121842860,1,01-JAN-20,3,C,51,5,42,M,1,2,NaN,NaN,NaN,42,0
1,2019,37347161,121842873,1,05-NOV-19,3,C,51,5,22,M,2,2,NaN,NaN,NaN,22,0
2,2019,37347178,121842921,1,20-NOV-19,1,N,51,5,26,M,1,2,NaN,NaN,NaN,26,0
3,2019,37347182,121846362,1,01-NOV-19,2,N,23,5,26,M,1,2,NaN,NaN,NaN,26,0
4,2019,37354913,121842972,1,02-AUG-19,1,N,16,5,25,F,2,2,NaN,NaN,NaN,25,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38378,2019,37765530,122997888,1,30-NOV-19,1,N,16,5,18,M,1,2,NaN,NaN,NaN,18,0
38379,2019,37760928,122997908,1,25-AUG-19,1,N,40,5,26,M,2,2,NaN,NaN,NaN,26,0
38380,2019,37756182,122977898,1,01-OCT-19,1,N,51,5,43,M,1,2,NaN,NaN,NaN,43,0
38381,2019,37760936,122997931,1,19-DEC-19,2,N,16,5,63,M,1,2,NaN,NaN,NaN,63,0
38382,2019,37756185,122997935,1,21-JUL-19,2,N,5,5,46,M,1,2,NaN,NaN,NaN,46,0

In [6]:
MO2019Offenses = MO2019Offenses.merge(Arrestees, how='left', on='INCIDENT_ID')

In [7]:
ArresteeType = pd.read_csv('NIBRS_ARREST_TYPE.csv')

In [8]:
ArresteeType

   ARREST_TYPE_ID ARREST_TYPE_CODE    ARREST_TYPE_NAME
0               1                O             On View
1               2                S    Summoned / Cited
2               3                T  Taken INTO Custody

In [9]:
MO2019Offenses = MO2019Offenses.merge(ArresteeType, how='left', on='ARREST_TYPE_ID')

In [10]:
ArresteeWeapon = pd.read_csv('NIBRS_ARRESTEE_WEAPON.csv')

In [11]:
ArresteeWeapon

       DATA_YEAR  ARRESTEE_ID  WEAPON_ID  NIBRS_ARRESTEE_WEAPON_ID
0           2019     32116382          1                  32142617
1           2019     32102541          1                  32128716
2           2019     32116432          1                  32142671
3           2019     32105584          1                  32142680
4           2019     32116455          1                  32128738
...          ...          ...        ...                       ...
38422       2019     37632015          1                  37965175
38423       2019     37635647          1                  37960574
38424       2019     37645225          1                  37965219
38425       2019     37632066          1                  37965223
38426       2019     37635659          1                  37960586

[38427 rows x 4 columns]

In [12]:
OffenseTypes = pd.read_csv('NIBRS_OFFENSE_TYPE.csv')

In [13]:
OffenseTypes

,OFFENSE_TYPE_ID,OFFENSE_CODE,OFFENSE_NAME,CRIME_AGAINST,CT_FLAG,HC_FLAG,HC_CODE,OFFENSE_CATEGORY_NAME,OFFENSE_GROUP
0,71,30A,Illegal Entry into the United States,Society,N,N,NaN,Other Offenses,A
1,72,30B,False Citizenship,Society,N,N,NaN,Other Offenses,A
2,73,30C,Smuggling Aliens,Society,N,N,NaN,Other Offenses,A
3,74,30D,Re-entry after Deportation,Society,N,N,NaN,Other Offenses,A
4,75,360,Failure to Register as a Sex Offender,Society,N,N,NaN,Other Offenses,A
...,...,...,...,...,...,...,...,...,...
81,65,90K,Failure to Appear,Society,N,N,NaN,Other Offenses,B
82,66,90L,Federal Resource Violations,Society,N,N,NaN,Other Offenses,B
83,67,90M,Perjury,Society,N,N,NaN,Other Offenses,B
84,69,101,Treason,Society,N,N,NaN,Other Offenses,A
85,70,103,Espionage,Society,N,N,NaN,Other Offenses,A

In [14]:
OffenseTypesValues = list(OffenseTypes['OFFENSE_NAME'].values)
OffenseTypesValues.sort()
# print(OffenseTypesValues)
STAR_relevant_offenses = ['Trespass of Real Property','Curfew/Loitering/Vagrancy Violations',
                          'Drug/Narcotic Violations','Drunkenness','Disorderly Conduct',
                         'Family Offenses, Nonviolent']

In [15]:
MO2019Offenses

,DATA_YEAR_x,OFFENSE_ID,INCIDENT_ID,OFFENSE_TYPE_ID_x,ATTEMPT_COMPLETE_FLAG,LOCATION_ID,NUM_PREMISES_ENTERED,METHOD_ENTRY_CODE,DATA_YEAR_y,ARRESTEE_ID,...,SEX_CODE,RACE_ID,ETHNICITY_ID,RESIDENT_CODE,UNDER_18_DISPOSITION_CODE,CLEARANCE_IND,AGE_RANGE_LOW_NUM,AGE_RANGE_HIGH_NUM,ARREST_TYPE_CODE,ARREST_TYPE_NAME
0,2019,133892120,109265381,45,C,7,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2019,133892125,109259840,16,C,13,NaN,NaN,2019.0,32600470.0,...,F,1.0,2.0,NaN,NaN,NaN,37.0,0.0,O,On View
2,2019,133887750,109266759,41,C,47,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2019,133887762,109265397,35,C,12,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2019,133882715,109259897,21,C,20,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
134060,2019,148794439,122990247,5,C,20,NaN,NaN,2019.0,37759864.0,...,M,1.0,2.0,NaN,NaN,NaN,24.0,0.0,S,Summoned / Cited
134061,2019,148794458,122990264,45,C,23,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
134062,2019,148790736,122990275,51,C,20,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
134063,2019,148794501,122985921,23,C,8,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
134064,2019,148790779,122990323,49,C,20,NaN,N,2019.0,37764688.0,...,M,1.0,2.0,NaN,H,NaN,17.0,0.0,O,On View

In [16]:
MO2019Offenses = MO2019Offenses.merge(OffenseTypes, how='left', left_on='OFFENSE_TYPE_ID_x',right_on='OFFENSE_TYPE_ID')

In [17]:
MO2019Offenses

,DATA_YEAR_x,OFFENSE_ID,INCIDENT_ID,OFFENSE_TYPE_ID_x,ATTEMPT_COMPLETE_FLAG,LOCATION_ID,NUM_PREMISES_ENTERED,METHOD_ENTRY_CODE,DATA_YEAR_y,ARRESTEE_ID,...,ARREST_TYPE_NAME,OFFENSE_TYPE_ID,OFFENSE_CODE,OFFENSE_NAME,CRIME_AGAINST,CT_FLAG,HC_FLAG,HC_CODE,OFFENSE_CATEGORY_NAME,OFFENSE_GROUP
0,2019,133892120,109265381,45,C,7,NaN,NaN,NaN,NaN,...,NaN,45,23H,All Other Larceny,Property,Y,N,NaN,Larceny/Theft Offenses,A
1,2019,133892125,109259840,16,C,13,NaN,NaN,2019.0,32600470.0,...,On View,16,35A,Drug/Narcotic Violations,Society,N,Y,NaN,Drug/Narcotic Offenses,A
2,2019,133887750,109266759,41,C,47,NaN,NaN,NaN,NaN,...,NaN,41,26B,Credit Card/Automated Teller Machine Fraud,Property,Y,Y,NaN,Fraud Offenses,A
3,2019,133887762,109265397,35,C,12,NaN,NaN,NaN,NaN,...,NaN,35,35B,Drug Equipment Violations,Society,N,Y,NaN,Drug/Narcotic Offenses,A
4,2019,133882715,109259897,21,C,20,NaN,NaN,NaN,NaN,...,NaN,21,240,Motor Vehicle Theft,Property,Y,Y,7.0,Motor Vehicle Theft,A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
134060,2019,148794439,122990247,5,C,20,NaN,NaN,2019.0,37759864.0,...,Summoned / Cited,5,290,Destruction/Damage/Vandalism of Property,Property,N,Y,11.0,Destruction/Damage/Vandalism of Property,A
134061,2019,148794458,122990264,45,C,23,NaN,NaN,NaN,NaN,...,NaN,45,23H,All Other Larceny,Property,Y,N,NaN,Larceny/Theft Offenses,A
134062,2019,148790736,122990275,51,C,20,NaN,NaN,NaN,NaN,...,NaN,51,13B,Simple Assault,Person,N,Y,9.0,Assault Offenses,A
134063,2019,148794501,122985921,23,C,8,NaN,NaN,NaN,NaN,...,NaN,23,23C,Shoplifting,Property,N,N,NaN,Larceny/Theft Offenses,A
134064,2019,148790779,122990323,49,C,20,NaN,N,2019.0,37764688.0,...,On View,49,220,Burglary/Breaking & Entering,Property,Y,Y,5.0,Burglary/Breaking & Entering,A

In [18]:
LocationRef = pd.read_csv('NIBRS_LOCATION_TYPE.csv')

In [19]:
LocationRef

    LOCATION_ID  LOCATION_CODE                                  LOCATION_NAME
0             1              1                         Air/Bus/Train Terminal
1             2              2                          Bank/Savings and Loan
2             3              3                                  Bar/Nightclub
3             4              4                 Church/Synagogue/Temple/Mosque
4             5              5                     Commercial/Office Building
5             6              6                              Construction Site
6             7              7                              Convenience Store
7             8              8                      Department/Discount Store
8            10             10                                    Field/Woods
9            11             11                     Government/Public Building
10           12             12                            Grocery/Supermarket
11           13             13             Highway/Road/Alley/Street/Sidewalk
12           14             14                               Hotel/Motel/Etc.
13           15             15  Jail/Prison/Penitentiary/Corrections Facility
14           16             16                            Lake/Waterway/Beach
15           17             17                                   Liquor Store
16           18             18                        Parking/Drop Lot/Garage
17           19             19                        Rental Storage Facility
18           20             20                                 Residence/Home
19           21             21                                     Restaurant
20           22             22                                 School/College
21           23             23                            Service/Gas Station
22           24             24                                Specialty Store
23           25             25                                  Other/Unknown
24           26             37                  Abandoned/Condemned Structure
25           27             38                                 Amusement Park
26           28             39             Arena/Stadium/Fairgrounds/Coliseum
27           29             40                         ATM Separate from Bank
28           30             41                       Auto Dealership New/Used
29           31             42                                Camp/Campground
30           32             44                               Daycare Facility
31           33             45              Dock/Wharf/Freight/Modal Terminal
32           34             46                                  Farm Facility
33           35             47            Gambling Facility/Casino/Race Track
34           36             48                                Industrial Site
35           37             49                          Military Installation
36           38             50                                Park/Playground
37           39             51                                      Rest Area
38           40             52                      School-College/University
39           41             53                    School-Elementary/Secondary
40           42             54                       Shelter-Mission/Homeless
41           43             55                                  Shopping Mall
42           44             56                                   Tribal Lands
43           45             57                               Community Center
44           46              9            Drug Store/Doctor's Office/Hospital
45           47             58                                     Cyberspace
46            0              0                                  Not Specified

In [20]:
MO2019Offenses = MO2019Offenses.merge(LocationRef, how='left', on='LOCATION_ID')

In [21]:
MO2019Offenses

,DATA_YEAR_x,OFFENSE_ID,INCIDENT_ID,OFFENSE_TYPE_ID_x,ATTEMPT_COMPLETE_FLAG,LOCATION_ID,NUM_PREMISES_ENTERED,METHOD_ENTRY_CODE,DATA_YEAR_y,ARRESTEE_ID,...,OFFENSE_CODE,OFFENSE_NAME,CRIME_AGAINST,CT_FLAG,HC_FLAG,HC_CODE,OFFENSE_CATEGORY_NAME,OFFENSE_GROUP,LOCATION_CODE,LOCATION_NAME
0,2019,133892120,109265381,45,C,7,NaN,NaN,NaN,NaN,...,23H,All Other Larceny,Property,Y,N,NaN,Larceny/Theft Offenses,A,7,Convenience Store
1,2019,133892125,109259840,16,C,13,NaN,NaN,2019.0,32600470.0,...,35A,Drug/Narcotic Violations,Society,N,Y,NaN,Drug/Narcotic Offenses,A,13,Highway/Road/Alley/Street/Sidewalk
2,2019,133887750,109266759,41,C,47,NaN,NaN,NaN,NaN,...,26B,Credit Card/Automated Teller Machine Fraud,Property,Y,Y,NaN,Fraud Offenses,A,58,Cyberspace
3,2019,133887762,109265397,35,C,12,NaN,NaN,NaN,NaN,...,35B,Drug Equipment Violations,Society,N,Y,NaN,Drug/Narcotic Offenses,A,12,Grocery/Supermarket
4,2019,133882715,109259897,21,C,20,NaN,NaN,NaN,NaN,...,240,Motor Vehicle Theft,Property,Y,Y,7.0,Motor Vehicle Theft,A,20,Residence/Home
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
134060,2019,148794439,122990247,5,C,20,NaN,NaN,2019.0,37759864.0,...,290,Destruction/Damage/Vandalism of Property,Property,N,Y,11.0,Destruction/Damage/Vandalism of Property,A,20,Residence/Home
134061,2019,148794458,122990264,45,C,23,NaN,NaN,NaN,NaN,...,23H,All Other Larceny,Property,Y,N,NaN,Larceny/Theft Offenses,A,23,Service/Gas Station
134062,2019,148790736,122990275,51,C,20,NaN,NaN,NaN,NaN,...,13B,Simple Assault,Person,N,Y,9.0,Assault Offenses,A,20,Residence/Home
134063,2019,148794501,122985921,23,C,8,NaN,NaN,NaN,NaN,...,23C,Shoplifting,Property,N,N,NaN,Larceny/Theft Offenses,A,8,Department/Discount Store
134064,2019,148790779,122990323,49,C,20,NaN,N,2019.0,37764688.0,...,220,Burglary/Breaking & Entering,Property,Y,Y,5.0,Burglary/Breaking & Entering,A,20,Residence/Home

In [22]:
Incidents = pd.read_csv('NIBRS_incident.csv')

In [23]:
Incidents

,DATA_YEAR,AGENCY_ID,INCIDENT_ID,NIBRS_MONTH_ID,CARGO_THEFT_FLAG,SUBMISSION_DATE,INCIDENT_DATE,REPORT_DATE_FLAG,INCIDENT_HOUR,CLEARED_EXCEPT_ID,CLEARED_EXCEPT_DATE,INCIDENT_STATUS,DATA_HOME,ORIG_FORMAT,DID
0,2019,9960,116135030,9191064,NaN,23-SEP-19,06-AUG-19,NaN,19.0,6,NaN,0,C,F,56536880
1,2019,9761,111056480,8985492,Y,21-MAY-19,11-MAR-19,NaN,8.0,6,NaN,0,C,F,46357401
2,2019,9761,111048015,8985492,NaN,21-MAY-19,03-MAR-19,NaN,1.0,6,NaN,0,C,F,46355347
3,2019,9761,111048017,8985492,NaN,21-MAY-19,07-MAR-19,NaN,23.0,6,NaN,0,C,F,46362702
4,2019,9761,111048022,8985492,N,21-MAY-19,15-MAR-19,NaN,16.0,6,NaN,0,C,F,46355357
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
107762,2019,10043,122997194,8152674,N,31-MAR-20,22-FEB-19,NaN,16.0,6,NaN,0,C,F,70662679
107763,2019,10043,123067626,8221632,NaN,06-APR-20,01-NOV-19,NaN,15.0,6,NaN,0,C,F,70927660
107764,2019,10043,122358732,8145012,NaN,17-MAR-20,21-JAN-19,NaN,4.0,6,NaN,0,C,F,69415433
107765,2019,10043,122358736,8145012,NaN,17-MAR-20,21-JAN-19,NaN,23.0,6,NaN,0,C,F,69409314
107766,2019,10043,122358747,8152674,NaN,17-MAR-20,01-FEB-19,NaN,8.0,6,NaN,0,C,F,69415464

In [24]:
MO2019Offenses = MO2019Offenses.merge(Incidents, how='left', on='INCIDENT_ID')

In [25]:
Agencies = pd.read_csv('agencies.csv')

In [26]:
# Agencies.COUNTY_NAME.values
pd.set_option('display.max_columns', None)
# Agencies['PUB_AGENCY_NAME'].values
Agencies#.groupby(['AGENCY_TYPE_NAME'])

,YEARLY_AGENCY_ID,AGENCY_ID,DATA_YEAR,ORI,LEGACY_ORI,COVERED_BY_LEGACY_ORI,DIRECT_CONTRIBUTOR_FLAG,DORMANT_FLAG,DORMANT_YEAR,REPORTING_TYPE,UCR_AGENCY_NAME,NCIC_AGENCY_NAME,PUB_AGENCY_NAME,PUB_AGENCY_UNIT,AGENCY_STATUS,STATE_ID,STATE_NAME,STATE_ABBR,STATE_POSTAL_ABBR,DIVISION_CODE,DIVISION_NAME,REGION_CODE,REGION_NAME,REGION_DESC,AGENCY_TYPE_NAME,POPULATION,SUBMITTING_AGENCY_ID,SAI,SUBMITTING_AGENCY_NAME,SUBURBAN_AREA_FLAG,POPULATION_GROUP_ID,POPULATION_GROUP_CODE,POPULATION_GROUP_DESC,PARENT_POP_GROUP_CODE,PARENT_POP_GROUP_DESC,MIP_FLAG,POP_SORT_ORDER,SUMMARY_RAPE_DEF,PE_REPORTED_FLAG,MALE_OFFICER,MALE_CIVILIAN,PED.MALE_OFFICER+PED.MALE_CIVILIAN,FEMALE_OFFICER,FEMALE_CIVILIAN,PED.FEMALE_CIVILIAN+PED.FEMALE_OFFICER,0,0.1,NIBRS_CERT_DATE,NIBRS_START_DATE,NIBRS_LEOKA_START_DATE,NIBRS_CT_START_DATE,NIBRS_MULTI_BIAS_START_DATE,NIBRS_OFF_ETH_START_DATE,COVERED_FLAG,COUNTY_NAME,MSA_NAME,PUBLISHABLE_FLAG,PARTICIPATED,NIBRS_PARTICIPATED
0,94802019,9480,2019,MO0010600,MO0010600,NaN,N,N,NaN,I,TRUMAN STATE UNIVERSITY,TRUMAN STATE UNIVERSITY,Truman State University,NaN,A,28,Missouri,MO,MO,4,West North Central,2,Midwest,Region II,University or College,0,23376,MOUCR0001,Missouri State Highway Patrol UCR Program Offi...,N,11,7,"Cities under 2,500",7,"Cities under 2,500",N,2,R,N,NaN,NaN,NaN,NaN,NaN,NaN,0,0,01-OCT-05,01-SEP-19,01-SEP-19,01-SEP-19,01-SEP-19,01-SEP-19,N,ADAIR,Non-MSA,Y,Y,Y
1,95072019,9507,2019,MO0070200,MO0070200,NaN,N,N,NaN,I,BUTLER,BUTLER,Butler,NaN,A,28,Missouri,MO,MO,4,West North Central,2,Midwest,Region II,City,4017,23376,MOUCR0001,Missouri State Highway Patrol UCR Program Offi...,Y,10,6,"Cities from 2,500 thru 9,999",6,"Cities from 2,500 thru 9,999",N,2,R,Y,9.0,4.0,13.0,0.0,2.0,2.0,0,0,01-OCT-05,01-DEC-19,01-DEC-19,01-APR-20,01-APR-20,01-APR-20,N,BATES,"Kansas City, MO-KS",Y,Y,Y
2,95092019,9509,2019,MO0080000,MO0080000,NaN,N,N,NaN,I,BENTON,BENTON,Benton,NaN,A,28,Missouri,MO,MO,4,West North Central,2,Midwest,Region II,County,14763,23376,MOUCR0001,Missouri State Highway Patrol UCR Program Offi...,N,15,8C,"Non-MSA counties from 10,000 thru 24,999",8,Non-MSA Counties,N,3,R,Y,15.0,7.0,22.0,2.0,3.0,5.0,0,0,01-OCT-05,01-OCT-17,01-OCT-17,01-MAR-20,01-MAR-20,01-MAR-20,N,BENTON,Non-MSA,Y,Y,Y
3,95172019,9517,2019,MO0100200,MO0100200,NaN,N,N,NaN,I,COLUMBIA,COLUMBIA,Columbia,NaN,A,28,Missouri,MO,MO,4,West North Central,2,Midwest,Region II,City,125017,23376,MOUCR0001,Missouri State Highway Patrol UCR Program Offi...,N,6,2,"Cities from 100,000 thru 249,999",2,"Cities from 100,000 thru 249,999",Y,1,R,Y,134.0,16.0,150.0,24.0,21.0,45.0,0,0,01-OCT-05,01-OCT-19,01-OCT-19,01-OCT-19,01-OCT-19,01-OCT-19,N,BOONE,"Columbia, MO",Y,Y,Y
4,95222019,9522,2019,MO0110000,MO0110000,NaN,N,N,NaN,I,BUCHANAN,BUCHANAN,Buchanan,NaN,A,28,Missouri,MO,MO,4,West North Central,2,Midwest,Region II,County,12499,23376,MOUCR0001,Missouri State Highway Patrol UCR Program Offi...,Y,21,9C,"MSA counties from 10,000 thru 24,999",9,MSA Counties,N,3,R,Y,58.0,13.0,71.0,11.0,24.0,35.0,0,0,01-OCT-05,01-MAR-18,01-MAR-18,01-FEB-19,01-APR-18,01-APR-18,N,BUCHANAN,"St. Joseph, MO-KS",Y,Y,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80,101442019,10144,2019,MO1110300,MO1110300,NaN,N,N,NaN,I,POTOSI,POTOSI,Potosi,NaN,A,28,Missouri,MO,MO,4,West North Central,2,Midwest,Region II,City,2609,23376,MOUCR0001,Missouri State Highway Patrol UCR Program Offi...,N,10,6,"Cities from 2,500 thru 9,999",6,"Cities from 2,500 thru 9,999",N,2,R,Y,9.0,0.0,9.0,1.0,1.0,2.0,0,0,01-OCT-05,01-AUG-19,01-AUG-19,01-AUG-19,01-AUG-19,01-AUG-19,N,WASHINGTON,Non-MSA,Y,Y,Y
81,101612019,10161,2019,MOKPD0000,MOKPD0000,NaN,N,N,NaN,I,KANSAS CITY,KANSAS CITY,Kansas City,NaN,A,28,Missouri,MO,MO,4,West North Central,2,Midwest,Region II,City,495964,23376,MOUCR0001,Missouri State Highway Patrol UCR Program Offi...,N,5,1C,"Cities from 250,000 thru 499,999",1,"All cities 250,000 or over",Y,1,R,Y,1105.0,173.0,1278.0,194.0,347.0,541.0,0,0,01-OCT-05,01-JAN-10,01-JAN-10,01-JAN-19,01-JAN-13,01-JAN-13,N,CASS; PLATTE; CLAY; JACKSON,"Kansas City, MO-KS",Y,Y,Y
82,101622019,10162,2019,MOMHP0000,MOMHP0000,NaN,N,N,NaN,I,MO STATE HIGHWAY PATROL,MO STATE HIGHWAY PATROL,Missouri State Highway Patrol,NaN,A,28,Missouri,MO,MO,4,West North Central,2,Midwest,Region II,State Police,0,23376,MOUCR0001,Missouri State Highway Patrol UCR Program Offi...,N,17,8E,Non-MSA State Police,8,Non-MSA Counties,N,3,R,Y,1168.0,524.0,1692.0,61.0,581.0,642.0,0,0,01-OCT-05,01-JUL-18,01-JUL-18,01-JAN-19,01-JUL-18,01-JUL-18,N,NaN,Non-MSA,Y,Y,Y
83,101632019,10163,2019,MOMHP0700,MOMHP0700,NaN,N,N,NaN,I,GAMING COMMISSION ENF D,"GAMING COMMISSION, ENF D",Gaming Commission,Enforcement Division,A,28,Missouri,MO,MO,4,West North Central,2,Midwest,Region II,Other State Agency,0,23376,MOUCR0001,Missouri State Highway Patrol UCR Program Offi...,N,11,7,"Cities under 2,500",7,"Cities under 2,500",N,2,R,Y,100.0,0.0,100.0,11.0,3.0,14.0,0,0,01-OCT-05,01-JUL-18,01-JUL-18,01-FEB-19,01-JUL-18,01-JUL-18,N,NaN,Non-MSA,Y,Y,Y
84,255872019,25587,2019,MO0922400,MO0922400,NaN,N,N,NaN,I,ST. CHARLES COUNTY PD,NaN,St. Charles County Police Department,NaN,A,28,Missouri,MO,MO,4,West North Central,2,Midwest,Region II,County,119556,23376,MOUCR0001,Missouri State Highway Patrol UCR Program Offi...,Y,19,9A,"MSA counties 100,000 or over",9,MSA Counties,Y,3,R,Y,133.0,10.0,143.0,10.0,27.0,37.0,0,0,01-OCT-05,01-JUN-19,01-JUN-19,01-JUN-19,01-JUN-19,01-JUN-19,N,ST CHARLES,"St. Louis, MO-IL",Y,Y,Y

In [27]:
MO2019Offenses = MO2019Offenses.merge(Agencies, how='left', on='AGENCY_ID')

In [28]:
#Want to get counts by unique agency
MO2019Offenses.groupby(['AGENCY_TYPE_NAME','OFFENSE_NAME'])['OFFENSE_NAME'].count()

AGENCY_TYPE_NAME       OFFENSE_NAME
City                   Aggravated Assault                             4990
                       All Other Larceny                              8714
                       Animal Cruelty                                   47
                       Arson                                           264
                       Assisting or Promoting Prostitution              17
                                                                      ...
University or College  Theft From Building                              36
                       Theft From Motor Vehicle                         44
                       Theft of Motor Vehicle Parts or Accessories       4
                       Weapon Law Violations                             2
                       Wire Fraud                                        1
Name: OFFENSE_NAME, Length: 164, dtype: int64

In [29]:
Weapons = pd.read_csv('NIBRS_WEAPON.csv')

In [30]:
Weapons

       DATA_YEAR  WEAPON_ID  OFFENSE_ID  NIBRS_WEAPON_ID
0           2019         12   132156214         24307162
1           2019         12   132161231         24302626
2           2019         12   132161249         24307171
3           2019         12   132156369         24297661
4           2019         20   132156376         24297662
...          ...        ...         ...              ...
26248       2019         11   136261759         25352642
26249       2019         12   136256105         25345069
26250       2019         12   136258865         25352682
26251       2019         12   136266141         25345090
26252       2019         12   136258879         25349156

[26253 rows x 4 columns]

In [31]:
MO2019Offenses = MO2019Offenses.merge(Weapons, how='left', on='OFFENSE_ID')

In [32]:
MO2019Offenses

,DATA_YEAR_x,OFFENSE_ID,INCIDENT_ID,OFFENSE_TYPE_ID_x,ATTEMPT_COMPLETE_FLAG,LOCATION_ID,NUM_PREMISES_ENTERED,METHOD_ENTRY_CODE,DATA_YEAR_y,ARRESTEE_ID,ARRESTEE_SEQ_NUM,ARREST_DATE,ARREST_TYPE_ID,MULTIPLE_INDICATOR,OFFENSE_TYPE_ID_y,AGE_ID,AGE_NUM,SEX_CODE,RACE_ID,ETHNICITY_ID,RESIDENT_CODE,UNDER_18_DISPOSITION_CODE,CLEARANCE_IND,AGE_RANGE_LOW_NUM,AGE_RANGE_HIGH_NUM,ARREST_TYPE_CODE,ARREST_TYPE_NAME,OFFENSE_TYPE_ID,OFFENSE_CODE,OFFENSE_NAME,CRIME_AGAINST,CT_FLAG,HC_FLAG,HC_CODE,OFFENSE_CATEGORY_NAME,OFFENSE_GROUP,LOCATION_CODE,LOCATION_NAME,DATA_YEAR_x,AGENCY_ID,NIBRS_MONTH_ID,CARGO_THEFT_FLAG,SUBMISSION_DATE,INCIDENT_DATE,REPORT_DATE_FLAG,INCIDENT_HOUR,CLEARED_EXCEPT_ID,CLEARED_EXCEPT_DATE,INCIDENT_STATUS,DATA_HOME,ORIG_FORMAT,DID,YEARLY_AGENCY_ID,DATA_YEAR_y,ORI,LEGACY_ORI,COVERED_BY_LEGACY_ORI,DIRECT_CONTRIBUTOR_FLAG,DORMANT_FLAG,DORMANT_YEAR,REPORTING_TYPE,UCR_AGENCY_NAME,NCIC_AGENCY_NAME,PUB_AGENCY_NAME,PUB_AGENCY_UNIT,AGENCY_STATUS,STATE_ID,STATE_NAME,STATE_ABBR,STATE_POSTAL_ABBR,DIVISION_CODE,DIVISION_NAME,REGION_CODE,REGION_NAME,REGION_DESC,AGENCY_TYPE_NAME,POPULATION,SUBMITTING_AGENCY_ID,SAI,SUBMITTING_AGENCY_NAME,SUBURBAN_AREA_FLAG,POPULATION_GROUP_ID,POPULATION_GROUP_CODE,POPULATION_GROUP_DESC,PARENT_POP_GROUP_CODE,PARENT_POP_GROUP_DESC,MIP_FLAG,POP_SORT_ORDER,SUMMARY_RAPE_DEF,PE_REPORTED_FLAG,MALE_OFFICER,MALE_CIVILIAN,PED.MALE_OFFICER+PED.MALE_CIVILIAN,FEMALE_OFFICER,FEMALE_CIVILIAN,PED.FEMALE_CIVILIAN+PED.FEMALE_OFFICER,0,0.1,NIBRS_CERT_DATE,NIBRS_START_DATE,NIBRS_LEOKA_START_DATE,NIBRS_CT_START_DATE,NIBRS_MULTI_BIAS_START_DATE,NIBRS_OFF_ETH_START_DATE,COVERED_FLAG,COUNTY_NAME,MSA_NAME,PUBLISHABLE_FLAG,PARTICIPATED,NIBRS_PARTICIPATED,DATA_YEAR,WEAPON_ID,NIBRS_WEAPON_ID
0,2019,133892120,109265381,45,C,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,45,23H,All Other Larceny,Property,Y,N,NaN,Larceny/Theft Offenses,A,7,Convenience Store,2019,9543,8913644,N,08-APR-19,14-MAR-19,NaN,13.0,6,NaN,0,C,F,43024701,95432019,2019,MO0150200,MO0150200,NaN,N,N,NaN,I,OSAGE BEACH,OSAGE BEACH,Osage Beach,NaN,A,28,Missouri,MO,MO,4,West North Central,2,Midwest,Region II,City,4598,23376,MOUCR0001,Missouri State Highway Patrol UCR Program Offi...,N,10,6,"Cities from 2,500 thru 9,999",6,"Cities from 2,500 thru 9,999",N,2,R,Y,17.0,0.0,17.0,3.0,4.0,7.0,0,0,01-OCT-05,01-MAR-19,01-MAR-19,01-MAR-19,01-MAR-19,01-MAR-19,N,MILLER; CAMDEN,Non-MSA,Y,Y,Y,NaN,NaN,NaN
1,2019,133892125,109259840,16,C,13,NaN,NaN,2019.0,32600470.0,1.0,24-FEB-19,1.0,C,16.0,5.0,37.0,F,1.0,2.0,NaN,NaN,NaN,37.0,0.0,O,On View,16,35A,Drug/Narcotic Violations,Society,N,Y,NaN,Drug/Narcotic Offenses,A,13,Highway/Road/Alley/Street/Sidewalk,2019,9541,8768580,NaN,08-APR-19,24-FEB-19,NaN,3.0,6,NaN,0,C,F,43027810,95412019,2019,MO0150000,MO0150000,NaN,N,N,NaN,I,CAMDEN,CAMDEN,Camden,NaN,A,28,Missouri,MO,MO,4,West North Central,2,Midwest,Region II,County,36589,23376,MOUCR0001,Missouri State Highway Patrol UCR Program Offi...,N,14,8B,"Non-MSA counties from 25,000 thru 99,999",8,Non-MSA Counties,N,3,R,Y,47.0,16.0,63.0,7.0,23.0,30.0,0,0,01-OCT-05,01-FEB-19,01-FEB-19,01-FEB-19,01-FEB-19,01-FEB-19,N,CAMDEN,Non-MSA,Y,Y,Y,NaN,NaN,NaN
2,2019,133887750,109266759,41,C,47,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,41,26B,Credit Card/Automated Teller Machine Fraud,Property,Y,Y,NaN,Fraud Offenses,A,58,Cyberspace,2019,9543,8913644,N,08-APR-19,07-MAR-19,NaN,9.0,6,NaN,0,C,F,43031655,95432019,2019,MO0150200,MO0150200,NaN,N,N,NaN,I,OSAGE BEACH,OSAGE BEACH,Osage Beach,NaN,A,28,Missouri,MO,MO,4,West North Central,2,Midwest,Region II,City,4598,23376,MOUCR0001,Missouri State Highway Patrol UCR Program Offi...,N,10,6,"Cities from 2,500 thru 9,999",6,"Cities from 2,500 thru 9,999",N,2,R,Y,17.0,0.0,17.0,3.0,4.0,7.0,0,0,01-OCT-05,01-MAR-19,01-MAR-19,01-MAR-19,01-MAR-19,01-MAR-19,N,MILLER; CAMDEN,Non-MSA,Y,Y,Y,NaN,NaN,NaN
3,2019,133887762,109265397,35,C,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,35,35B,Drug Equipment Violations,Society,N,Y,NaN,Drug/Narcotic Offenses,A,12,Grocery/Supermarket,2019,9541,8911642,NaN,08-APR-19,10-MAR-19,NaN,0.0,6,NaN,0,C,F,43024720,95412019,2019,MO0150000,MO0150000,NaN,N,N,NaN,I,CAMDEN,CAMDEN,Camden,NaN,A,28,Missouri,MO,MO,4,West North Central,2,Midwest,Region II,County,36589,23376,MOUCR0001,Missouri State Highway Patrol UCR Program Offi...,N,14,8B,"Non-MSA counties from 25,000 thru 99,999",8,Non-MSA Counties,N,3,R,Y,47.0,16.0,63.0,7.0,23.0,30.0,0,0,01-OCT-05,01-FEB-19,01-FEB-19,01-FEB-19,01-FEB-19,01-FEB-19,N,CAMDEN,Non-MSA,Y,Y,Y,NaN,NaN,NaN
4,2019,133882715,109259897,21,C,20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21,240,Motor Vehicle Theft,Property,Y,Y,7.0,Motor Vehicle Theft,A,20,Residence/Home,2019,9562,8152650,N,08-APR-19,26-FEB-19,NaN,4.0,6,NaN,0,C,F,43031768,95622019,2019,MO0190400,MO0190400,NaN,N,N,NaN,I,HARRISONVILLE,HARRISONVILLE,Harrisonville,NaN,A,28,Missouri,MO,MO,4,West North Central,2,Midwest,Region II,City,10095,23376,MOUCR0001,Missouri State Highway Patrol UCR Program Offi...,Y,9,5,"Cities from 10,000 thru 24,999",5,"Cities from 10,000 thru 24,999",N,2,R,Y,21.0,0.0,21.0,2.0,8.0,10.0,0,0,01-OCT-05,01-FEB-18,01-FEB-18,01-MAR-19,01-FEB-18,01-FEB-18,N,CASS,"Kansas City, MO-KS",Y,Y,Y,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
134610,2019,148794439,122990247,5,C,20,NaN,NaN,2019.0,37759864.0,1.0,17-DEC-19,2.0,N,5.0,5.0,24.0,M,1.0,2.0,NaN,NaN,NaN,24.0,0.0,S,Summoned / Cited,5,290,Destruction/Damage/Vandalism of Property,Property,N,Y,11.0,Destruction/Damage/Vandalism of Property,A,20,Residence/Home,2019,9517,11218604,NaN,31-MAR-20,17-DEC-19,NaN,6.0,6,NaN,0,C,F,70648394,95172019,2019,MO0100200,MO0100200,NaN,N,N,NaN,I,COLUMBIA,COLUMBIA,Columbia,NaN,A,28,Missouri,MO,MO,4,West North Central,2,Midwest,Region II,City,125017,23376,MOUCR0001,Missouri State Highway Patrol UCR Program Offi...,N,6,2,"Cities from 100,000 thru 249,999",2,"Cities from 100,000 thru 249,999",Y,1,R,Y,134.0,16.0,150.0,24.0,21.0,45.0,0,0,01-OCT-05,01-OCT-19,01-OCT-19,01-OCT-19,01-OCT-19,01-OCT-19,N,BOONE,"Columbia, MO",Y,Y,Y,NaN,NaN,NaN
134611,2019,148794458,122990264,45,C,23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,45,23H,All Other Larceny,Property,Y,N,NaN,Larceny/Theft Offenses,A,23,Service/Gas Station,2019,9720,10527962,N,31-MAR-20,27-OCT-19,NaN,15.0,6,NaN,0,C,F,70653396,97202019,2019,MO0480600,MO0480600,NaN,N,N,NaN,I,INDEPENDENCE,INDEPENDENCE,Independence,NaN,A,28,Missouri,MO,MO,4,West North Central,2,Midwest,Region II,City,116931,23376,MOUCR0001,Missouri State Highway Patrol UCR Program Offi...,N,6,2,"Cities from 100,000 thru 249,999",2,"Cities from 100,000 thru 249,999",Y,1,R,Y,180.0,19.0,199.0,19.0,54.0,73.0,0,0,01-OCT-05,01-FEB-19,01-FEB-19,01-FEB-19,01-FEB-19,01-FEB-19,N,JACKSON,"Kansas City, MO-KS",Y,Y,Y,NaN,NaN,NaN
134612,2019,148790736,122990275,51,C,20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,51,13B,Simple Assault,Person,N,Y,9.0,Assault Offenses,A,20,Residence/Home,2019,9720,9086163,NaN,31-MAR-20,13-JUN-19,NaN,9.0,6,NaN,0,C,F,70653429,97202019,2019,MO0480600,MO0480600,NaN,N,N,NaN,I,INDEPENDENCE,INDEPENDENCE,Independence,NaN,A,28,Missouri,MO,MO,4,West North Central,2,Midwest,Region II,City,116931,23376,MOUCR0001,Missouri State Highway Patrol UCR Program Offi...,N,6,2,"Cities from 100,000 thru 249,999",2,"Cities from 100,000 thru 249,999",Y,1,R,Y,180.0,19.0,199.0,19.0,54.0,73.0,0,0,01-OCT-05,01-FEB-19,01-FEB-19,01-FEB-19,01-FEB-19,01-FEB-19,N,JACKSON,"Kansas City, MO-KS",Y,Y,Y,2019.0,12.0,29652294.0
134613,2019,148794501,122985921,23,C,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23,23C,Shoplifting,Property,N,N,NaN,Larceny/Theft Offenses,A,8,Department/Discount Store,2019,9517,11218604,NaN,31-MAR-20,17-DEC-19,NaN,15.0,6,NaN,0,C,F,70653474,95172019,2019,MO0100200,MO0100200,NaN,N,N,NaN,I,COLUMBIA,COLUMBIA,Columbia,NaN,A,28,Missouri,MO,MO,4,West North Central,2,Midwest,Region II,City,125017,23376,MOUCR0001,Missouri State Highway Patrol UCR Program Offi...,N,6,2,"Cities from 100,000 thru 249,999",2,"Cities from 100,000 thru 249,999",Y,1,R,Y,134.0,16.0,150.0,24.0,21.0,45.0,0,0,01-OCT-05,01-OCT-19,01-OCT-19,01-OCT-19,01-OCT-19,01-OCT-19,N,BOONE,"Columbia, MO",Y,Y,Y,NaN,NaN,NaN
134614,2019,148790779,122990323,49,C,20,NaN,N,2019.0,37764688.0,1.0,05-NOV-19,1.0,N,49.0,5.0,17.0,M,1.0,2.0,NaN,H,NaN,17.0,0.0,O,On View,49,220,Burglary/Breaking & Entering,Property,Y,Y,5.0,Burglary/Breaking & Entering,A,20,Residence/Home,2019,9721,8221616,N,31-MAR-20,05-NOV-19,NaN,8.0,6,NaN,0,C,F,70648504,97212019,2019,MO0480700,MO0480700,NaN,N,N,NaN,I,LAKE LOTAWANA,LAKE LOTAWANA,Lake Lotawana,NaN,A,28,Missouri,MO,MO,4,West North Central,2,Midwest,Region II,City,2126,23376,MOUCR0001,Missouri State Highway Patrol UCR Program Offi...,Y,11,7,"Cities under 2,500",7,"Cities under 2,500",N,2,R,Y,4.0,0.0,4.0,0.0,0.0,0.0,0,0,01-OCT-05,01-APR-10,01-APR-10,01-FEB-19,01-APR-13,01-APR-13,N,JACKSON,"Kansas City, MO-KS",Y,Y,Y,NaN,NaN,NaN

In [33]:
WeaponType = pd.read_csv('NIBRS_WEAPON_TYPE.csv')

In [34]:
WeaponType

    WEAPON_ID WEAPON_CODE                      WEAPON_NAME SHR_FLAG
0          21         11A              Firearm (Automatic)        N
1          22         12A              Handgun (Automatic)        N
2          23         13A                Rifle (Automatic)        N
3          24         14A              Shotgun (Automatic)        N
4          25         15A        Other Firearm (Automatic)        N
5          26          55      Pushed or Thrown Out Window        Y
6          27          75                         Drowning        Y
7          28          80  Strangulation - Include Hanging        Y
8           1          01                          Unarmed        N
9           2          11                          Firearm        Y
10          3          12                          Handgun        Y
11          4          13                            Rifle        Y
12          5          14                          Shotgun        Y
13          6          15                    Other Firearm        Y
14          7          16        Lethal Cutting Instrument        N
15          8          17    Club/Blackjack/Brass Knuckles        N
16          9          20         Knife/Cutting Instrument        Y
17         10          30                     Blunt Object        Y
18         11          35             Motor Vehicle/Vessel        N
19         12          40                 Personal Weapons        Y
20         13          50                           Poison        Y
21         14          60                       Explosives        Y
22         15          65           Fire/Incendiary Device        Y
23         16          70   Drugs/Narcotics/Sleeping Pills        Y
24         17          85                     Asphyxiation        Y
25         18          90                            Other        Y
26         19          95                          Unknown        N
27         20          99                             None        N

In [35]:
MO2019Offenses = MO2019Offenses.merge(WeaponType, how='left', on='WEAPON_ID')

In [36]:
ArrestType = pd.read_csv('NIBRS_ARREST_TYPE.csv')

In [37]:
Offender = pd.read_csv('NIBRS_OFFENDER.csv')

In [38]:
Offender

,DATA_YEAR,OFFENDER_ID,INCIDENT_ID,OFFENDER_SEQ_NUM,AGE_ID,AGE_NUM,SEX_CODE,RACE_ID,ETHNICITY_ID,AGE_RANGE_LOW_NUM,AGE_RANGE_HIGH_NUM
0,2019,130978437,115243752,1,5.0,54.0,M,2.0,2.0,54.0,0.0
1,2019,130982474,115243753,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2019,130973899,115243754,1,5.0,24.0,F,1.0,2.0,24.0,0.0
3,2019,130978446,115234941,1,5.0,35.0,M,1.0,2.0,35.0,0.0
4,2019,130973900,115243757,1,5.0,28.0,M,2.0,2.0,28.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
124032,2019,138489525,121843151,1,5.0,21.0,M,2.0,2.0,21.0,0.0
124033,2019,138494203,121840885,1,5.0,42.0,F,1.0,3.0,42.0,0.0
124034,2019,138489740,121843343,1,5.0,27.0,M,1.0,2.0,27.0,0.0
124035,2019,138489781,121843380,1,5.0,47.0,M,1.0,2.0,47.0,0.0
124036,2019,138494414,121841071,1,4.0,NaN,U,0.0,3.0,NaN,NaN

In [39]:
MO2019Offenses = MO2019Offenses.merge(Offender, how='left', on='INCIDENT_ID')

In [40]:
MO2019Offenses

,DATA_YEAR_x,OFFENSE_ID,INCIDENT_ID,OFFENSE_TYPE_ID_x,ATTEMPT_COMPLETE_FLAG,LOCATION_ID,NUM_PREMISES_ENTERED,METHOD_ENTRY_CODE,DATA_YEAR_y,ARRESTEE_ID,ARRESTEE_SEQ_NUM,ARREST_DATE,ARREST_TYPE_ID,MULTIPLE_INDICATOR,OFFENSE_TYPE_ID_y,AGE_ID_x,AGE_NUM_x,SEX_CODE_x,RACE_ID_x,ETHNICITY_ID_x,RESIDENT_CODE,UNDER_18_DISPOSITION_CODE,CLEARANCE_IND,AGE_RANGE_LOW_NUM_x,AGE_RANGE_HIGH_NUM_x,ARREST_TYPE_CODE,ARREST_TYPE_NAME,OFFENSE_TYPE_ID,OFFENSE_CODE,OFFENSE_NAME,CRIME_AGAINST,CT_FLAG,HC_FLAG,HC_CODE,OFFENSE_CATEGORY_NAME,OFFENSE_GROUP,LOCATION_CODE,LOCATION_NAME,DATA_YEAR_x,AGENCY_ID,NIBRS_MONTH_ID,CARGO_THEFT_FLAG,SUBMISSION_DATE,INCIDENT_DATE,REPORT_DATE_FLAG,INCIDENT_HOUR,CLEARED_EXCEPT_ID,CLEARED_EXCEPT_DATE,INCIDENT_STATUS,DATA_HOME,ORIG_FORMAT,DID,YEARLY_AGENCY_ID,DATA_YEAR_y,ORI,LEGACY_ORI,COVERED_BY_LEGACY_ORI,DIRECT_CONTRIBUTOR_FLAG,DORMANT_FLAG,DORMANT_YEAR,REPORTING_TYPE,UCR_AGENCY_NAME,NCIC_AGENCY_NAME,PUB_AGENCY_NAME,PUB_AGENCY_UNIT,AGENCY_STATUS,STATE_ID,STATE_NAME,STATE_ABBR,STATE_POSTAL_ABBR,DIVISION_CODE,DIVISION_NAME,REGION_CODE,REGION_NAME,REGION_DESC,AGENCY_TYPE_NAME,POPULATION,SUBMITTING_AGENCY_ID,SAI,SUBMITTING_AGENCY_NAME,SUBURBAN_AREA_FLAG,POPULATION_GROUP_ID,POPULATION_GROUP_CODE,POPULATION_GROUP_DESC,PARENT_POP_GROUP_CODE,PARENT_POP_GROUP_DESC,MIP_FLAG,POP_SORT_ORDER,SUMMARY_RAPE_DEF,PE_REPORTED_FLAG,MALE_OFFICER,MALE_CIVILIAN,PED.MALE_OFFICER+PED.MALE_CIVILIAN,FEMALE_OFFICER,FEMALE_CIVILIAN,PED.FEMALE_CIVILIAN+PED.FEMALE_OFFICER,0,0.1,NIBRS_CERT_DATE,NIBRS_START_DATE,NIBRS_LEOKA_START_DATE,NIBRS_CT_START_DATE,NIBRS_MULTI_BIAS_START_DATE,NIBRS_OFF_ETH_START_DATE,COVERED_FLAG,COUNTY_NAME,MSA_NAME,PUBLISHABLE_FLAG,PARTICIPATED,NIBRS_PARTICIPATED,DATA_YEAR_x,WEAPON_ID,NIBRS_WEAPON_ID,WEAPON_CODE,WEAPON_NAME,SHR_FLAG,DATA_YEAR_y,OFFENDER_ID,OFFENDER_SEQ_NUM,AGE_ID_y,AGE_NUM_y,SEX_CODE_y,RACE_ID_y,ETHNICITY_ID_y,AGE_RANGE_LOW_NUM_y,AGE_RANGE_HIGH_NUM_y
0,2019,133892120,109265381,45,C,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,45,23H,All Other Larceny,Property,Y,N,NaN,Larceny/Theft Offenses,A,7,Convenience Store,2019,9543,8913644,N,08-APR-19,14-MAR-19,NaN,13.0,6,NaN,0,C,F,43024701,95432019,2019,MO0150200,MO0150200,NaN,N,N,NaN,I,OSAGE BEACH,OSAGE BEACH,Osage Beach,NaN,A,28,Missouri,MO,MO,4,West North Central,2,Midwest,Region II,City,4598,23376,MOUCR0001,Missouri State Highway Patrol UCR Program Offi...,N,10,6,"Cities from 2,500 thru 9,999",6,"Cities from 2,500 thru 9,999",N,2,R,Y,17.0,0.0,17.0,3.0,4.0,7.0,0,0,01-OCT-05,01-MAR-19,01-MAR-19,01-MAR-19,01-MAR-19,01-MAR-19,N,MILLER; CAMDEN,Non-MSA,Y,Y,Y,NaN,NaN,NaN,NaN,NaN,NaN,2019,123710966,1,5.0,52.0,F,1.0,2.0,52.0,0.0
1,2019,133892125,109259840,16,C,13,NaN,NaN,2019.0,32600470.0,1.0,24-FEB-19,1.0,C,16.0,5.0,37.0,F,1.0,2.0,NaN,NaN,NaN,37.0,0.0,O,On View,16,35A,Drug/Narcotic Violations,Society,N,Y,NaN,Drug/Narcotic Offenses,A,13,Highway/Road/Alley/Street/Sidewalk,2019,9541,8768580,NaN,08-APR-19,24-FEB-19,NaN,3.0,6,NaN,0,C,F,43027810,95412019,2019,MO0150000,MO0150000,NaN,N,N,NaN,I,CAMDEN,CAMDEN,Camden,NaN,A,28,Missouri,MO,MO,4,West North Central,2,Midwest,Region II,County,36589,23376,MOUCR0001,Missouri State Highway Patrol UCR Program Offi...,N,14,8B,"Non-MSA counties from 25,000 thru 99,999",8,Non-MSA Counties,N,3,R,Y,47.0,16.0,63.0,7.0,23.0,30.0,0,0,01-OCT-05,01-FEB-19,01-FEB-19,01-FEB-19,01-FEB-19,01-FEB-19,N,CAMDEN,Non-MSA,Y,Y,Y,NaN,NaN,NaN,NaN,NaN,NaN,2019,123706789,1,5.0,37.0,F,1.0,2.0,37.0,0.0
2,2019,133887750,109266759,41,C,47,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,41,26B,Credit Card/Automated Teller Machine Fraud,Property,Y,Y,NaN,Fraud Offenses,A,58,Cyberspace,2019,9543,8913644,N,08-APR-19,07-MAR-19,NaN,9.0,6,NaN,0,C,F,43031655,95432019,2019,MO0150200,MO0150200,NaN,N,N,NaN,I,OSAGE BEACH,OSAGE BEACH,Osage Beach,NaN,A,28,Missouri,MO,MO,4,West North Central,2,Midwest,Region II,City,4598,23376,MOUCR0001,Missouri State Highway Patrol UCR Program Offi...,N,10,6,"Cities from 2,500 thru 9,999",6,"Cities from 2,500 thru 9,999",N,2,R,Y,17.0,0.0,17.0,3.0,4.0,7.0,0,0,01-OCT-05,01-MAR-19,01-MAR-19,01-MAR-19,01-MAR-19,01-MAR-19,N,MILLER; CAMDEN,Non-MSA,Y,Y,Y,NaN,NaN,NaN,NaN,NaN,NaN,2019,123706794,1,4.0,NaN,U,0.0,3.0,NaN,NaN
3,2019,133887762,109265397,35,C,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,35,35B,Drug Equipment Violations,Society,N,Y,NaN,Drug/Narcotic Offenses,A,12,Grocery/Supermarket,2019,9541,8911642,NaN,08-APR-19,10-MAR-19,NaN,0.0,6,NaN,0,C,F,43024720,95412019,2019,MO0150000,MO0150000,NaN,N,N,NaN,I,CAMDEN,CAMDEN,Camden,NaN,A,28,Missouri,MO,MO,4,West North Central,2,Midwest,Region II,County,36589,23376,MOUCR0001,Missouri State Highway Patrol UCR Program Offi...,N,14,8B,"Non-MSA counties from 25,000 thru 99,999",8,Non-MSA Counties,N,3,R,Y,47.0,16.0,63.0,7.0,23.0,30.0,0,0,01-OCT-05,01-FEB-19,01-FEB-19,01-FEB-19,01-FEB-19,01-FEB-19,N,CAMDEN,Non-MSA,Y,Y,Y,NaN,NaN,NaN,NaN,NaN,NaN,2019,123716052,1,5.0,47.0,F,1.0,3.0,47.0,0.0
4,2019,133882715,109259897,21,C,20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21,240,Motor Vehicle Theft,Property,Y,Y,7.0,Motor Vehicle Theft,A,20,Residence/Home,2019,9562,8152650,N,08-APR-19,26-FEB-19,NaN,4.0,6,NaN,0,C,F,43031768,95622019,2019,MO0190400,MO0190400,NaN,N,N,NaN,I,HARRISONVILLE,HARRISONVILLE,Harrisonville,NaN,A,28,Missouri,MO,MO,4,West North Central,2,Midwest,Region II,City,10095,23376,MOUCR0001,Missouri State Highway Patrol UCR Program Offi...,Y,9,5,"Cities from 10,000 thru 24,999",5,"Cities from 10,000 thru 24,999",N,2,R,Y,21.0,0.0,21.0,2.0,8.0,10.0,0,0,01-OCT-05,01-FEB-18,01-FEB-18,01-MAR-19,01-FEB-18,01-FEB-18,N,CASS,"Kansas City, MO-KS",Y,Y,Y,NaN,NaN,NaN,NaN,NaN,NaN,2019,123706877,2,5.0,40.0,F,1.0,2.0,40.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
170607,2019,148794439,122990247,5,C,20,NaN,NaN,2019.0,37759864.0,1.0,17-DEC-19,2.0,N,5.0,5.0,24.0,M,1.0,2.0,NaN,NaN,NaN,24.0,0.0,S,Summoned / Cited,5,290,Destruction/Damage/Vandalism of Property,Property,N,Y,11.0,Destruction/Damage/Vandalism of Property,A,20,Residence/Home,2019,9517,11218604,NaN,31-MAR-20,17-DEC-19,NaN,6.0,6,NaN,0,C,F,70648394,95172019,2019,MO0100200,MO0100200,NaN,N,N,NaN,I,COLUMBIA,COLUMBIA,Columbia,NaN,A,28,Missouri,MO,MO,4,West North Central,2,Midwest,Region II,City,125017,23376,MOUCR0001,Missouri State Highway Patrol UCR Program Offi...,N,6,2,"Cities from 100,000 thru 249,999",2,"Cities from 100,000 thru 249,999",Y,1,R,Y,134.0,16.0,150.0,24.0,21.0,45.0,0,0,01-OCT-05,01-OCT-19,01-OCT-19,01-OCT-19,01-OCT-19,01-OCT-19,N,BOONE,"Columbia, MO",Y,Y,Y,NaN,NaN,NaN,NaN,NaN,NaN,2019,139868734,1,5.0,24.0,M,1.0,3.0,24.0,0.0
170608,2019,148794458,122990264,45,C,23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,45,23H,All Other Larceny,Property,Y,N,NaN,Larceny/Theft Offenses,A,23,Service/Gas Station,2019,9720,10527962,N,31-MAR-20,27-OCT-19,NaN,15.0,6,NaN,0,C,F,70653396,97202019,2019,MO0480600,MO0480600,NaN,N,N,NaN,I,INDEPENDENCE,INDEPENDENCE,Independence,NaN,A,28,Missouri,MO,MO,4,West North Central,2,Midwest,Region II,City,116931,23376,MOUCR0001,Missouri State Highway Patrol UCR Program Offi...,N,6,2,"Cities from 100,000 thru 249,999",2,"Cities from 100,000 thru 249,999",Y,1,R,Y,180.0,19.0,199.0,19.0,54.0,73.0,0,0,01-OCT-05,01-FEB-19,01-FEB-19,01-FEB-19,01-FEB-19,01-FEB-19,N,JACKSON,"Kansas City, MO-KS",Y,Y,Y,NaN,NaN,NaN,NaN,NaN,NaN,2019,139868753,1,5.0,35.0,M,2.0,2.0,35.0,0.0
170609,2019,148790736,122990275,51,C,20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,51,13B,Simple Assault,Person,N,Y,9.0,Assault Offenses,A,20,Residence/Home,2019,9720,9086163,NaN,31-MAR-20,13-JUN-19,NaN,9.0,6,NaN,0,C,F,70653429,97202019,2019,MO0480600,MO0480600,NaN,N,N,NaN,I,INDEPENDENCE,INDEPENDENCE,Independence,NaN,A,28,Missouri,MO,MO,4,West North Central,2,Midwest,Region II,City,116931,23376,MOUCR0001,Missouri State Highway Patrol UCR Program Offi...,N,6,2,"Cities from 100,000 thru 249,999",2,"Cities from 100,000 thru 249,999",Y,1,R,Y,180.0,19.0,199.0,19.0,54.0,73.0,0,0,01-OCT-05,01-FEB-19,01-FEB-19,01-FEB-19,01-FEB-19,01-FEB-19,N,JACKSON,"Kansas City, MO-KS",Y,Y,Y,2019.0,12.0,29652294.0,40,Personal Weapons,Y,2019,139868765,1,5.0,48.0,M,2.0,2.0,48.0,0.0
170610,2019,148794501,122985921,23,C,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23,23C,Shoplifting,Property,N,N,NaN,Larceny/Theft Offenses,A,8,Department/Discount Store,2019,9517,11218604,NaN,31-MAR-20,17-DEC-19,NaN,15.0,6,NaN,0,C,F,70653474,95172019,2019,MO0100200,MO0100200,NaN,N,N,NaN,I,COLUMBIA,COLUMBIA,Columbia,NaN,A,28,Missouri,MO,MO,4,West North Central,2,Midwest,Region II,City,125017,23376,MOUCR0001,Missouri State Highway Patrol UCR Program Offi...,N,6,2,"Cities from 100,000 thru 249,999",2,"Cities from 100,000 thru 249,999",Y,1,R,Y,134.0,16.0,150.0,24.0,21.0,45.0,0,0,01-OCT-05,01-OCT-19,01-OCT-19,01-OCT-19,01-OCT-19,01-OCT-19,N,BOONE,"Columbia, MO",Y,Y,Y,NaN,NaN,NaN,NaN,NaN,NaN,2019,139872070,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
170611,2019,148790779,122990323,49,C,20,NaN,N,2019.0,37764688.0,1.0,05-NOV-19,1.0,N,49.0,5.0,17.0,M,1.0,2.0,NaN,H,NaN,17.0,0.0,O,On View,49,220,Burglary/Breaking & Entering,Property,Y,Y,5.0,Burglary/Breaking & Entering,A,20,Residence/Home,2019,9721,8221616,N,31-MAR-20,05-NOV-19,NaN,8.0,6,NaN,0,C,F,70648504,97212019,2019,MO0480700,MO0480700,NaN,N,N,NaN,I,LAKE LOTAWANA,LAKE LOTAWANA,Lake Lotawana,NaN,A,28,Missouri,MO,MO,4,West North Central,2,Midwest,Region II,City,2126,23376,MOUCR0001,Missouri State Highway Patrol UCR Program Offi...,Y,11,7,"Cities under 2,500",7,"Cities under 2,500",N,2,R,Y,4.0,0.0,4.0,0.0,0.0,0.0,0,0,01-OCT-05,01-APR-10,01-APR-10,01-FEB-19,01-APR-13,01-APR-13,N,JACKSON,"Kansas City, MO-KS",Y,Y,Y,NaN,NaN,NaN,NaN,NaN,NaN,2019,139872099,1,5.0,17.0,M,1.0,2.0,17.0,0.0

In [41]:
Race = pd.read_csv('REF_RACE.csv')

In [42]:
Race

,RACE_ID,RACE_CODE,RACE_DESC,SORT_ORDER,START_YEAR,END_YEAR,NOTES
0,0,U,Unknown,98,NaN,NaN,Race is explicitly unknown
1,1,W,White,10,NaN,NaN,NaN
2,2,B,Black or African American,20,NaN,NaN,NaN
3,3,I,American Indian or Alaska Native,30,NaN,NaN,NaN
4,4,A,Asian,40,2013.0,NaN,Includes Asian Indian
5,5,AP,"Asian, Native Hawaiian, or Other Pacific Islander",41,1980.0,2012.0,Includes Asian Indian
6,6,C,Chinese,42,1960.0,1979.0,NaN
7,7,J,Japanese,43,1960.0,1979.0,NaN
8,8,P,Native Hawaiian or Other Pacific Islander,50,2013.0,NaN,NaN
9,9,O,Other,60,1960.0,1979.0,Includes Native Hawaiian or Other Pacific Isla...
10,98,M,Multiple,70,NaN,NaN,Used for groups with multiple races
11,99,NS,Not Specified,99,NaN,NaN,Race is not specified

In [43]:
MO2019Offenses = MO2019Offenses.merge(Race, how='left', left_on='RACE_ID_x',right_on='RACE_ID')

In [44]:
MO2019Offenses['OFFENSE_ID'] = MO2019Offenses['OFFENSE_ID'].astype(float)

In [45]:
set(MO2019Offenses.COUNTY_NAME.values)

{'ADAIR',
 'BATES',
 'BENTON',
 'BOONE',
 'BUCHANAN',
 'BUTLER',
 'CALDWELL',
 'CALLAWAY; COLE',
 'CAMDEN',
 'CASS',
 'CASS; PLATTE; CLAY; JACKSON',
 'CHARITON; LINN',
 'CHRISTIAN',
 'CLAY',
 'CLAY; RAY',
 'COOPER',
 'DEKALB; CLINTON',
 'DUNKLIN',
 'FRANKLIN',
 'GASCONADE',
 'HENRY',
 'HOWARD',
 'IRON',
 'JACKSON',
 'JASPER',
 'JOHNSON',
 'LACLEDE',
 'LAFAYETTE',
 'LAFAYETTE; JACKSON',
 'LINCOLN',
 'LIVINGSTON',
 'MCDONALD',
 'MILLER',
 'MILLER; CAMDEN',
 'MORGAN',
 'NEW MADRID',
 'NEWTON',
 'NEWTON; JASPER',
 'PERRY',
 'POLK',
 'SALINE',
 'SCOTT',
 'SHELBY',
 'ST CHARLES',
 'ST FRANCOIS',
 'ST LOUIS',
 'STE GENEVIEVE',
 'STODDARD',
 'TEXAS',
 'WASHINGTON',
 nan}

# Scott County Drilldown

In [46]:
ScottCO = MO2019Offenses[MO2019Offenses['COUNTY_NAME']=='SCOTT']

In [47]:
STAR_relevant_offenses = ['Trespass of Real Property','Curfew/Loitering/Vagrancy Violations',
                          'Drug/Narcotic Violations','Drunkenness','Disorderly Conduct',
                         'Family Offenses, Nonviolent','Simple Assault',
                          'Drug Equipment Violations','Destruction/Damage/Vandalism of Property']

In [48]:
ScottCO = ScottCO[ScottCO['OFFENSE_NAME'].isin(STAR_relevant_offenses)]

In [49]:
ScottCO = ScottCO[ScottCO['WEAPON_ID'].isnull()]

In [50]:
set(ScottCO.ARREST_TYPE_NAME.values)
ScottCO

,DATA_YEAR_x,OFFENSE_ID,INCIDENT_ID,OFFENSE_TYPE_ID_x,ATTEMPT_COMPLETE_FLAG,LOCATION_ID,NUM_PREMISES_ENTERED,METHOD_ENTRY_CODE,DATA_YEAR_y,ARRESTEE_ID,ARRESTEE_SEQ_NUM,ARREST_DATE,ARREST_TYPE_ID,MULTIPLE_INDICATOR,OFFENSE_TYPE_ID_y,AGE_ID_x,AGE_NUM_x,SEX_CODE_x,RACE_ID_x,ETHNICITY_ID_x,RESIDENT_CODE,UNDER_18_DISPOSITION_CODE,CLEARANCE_IND,AGE_RANGE_LOW_NUM_x,AGE_RANGE_HIGH_NUM_x,ARREST_TYPE_CODE,ARREST_TYPE_NAME,OFFENSE_TYPE_ID,OFFENSE_CODE,OFFENSE_NAME,CRIME_AGAINST,CT_FLAG,HC_FLAG,HC_CODE,OFFENSE_CATEGORY_NAME,OFFENSE_GROUP,LOCATION_CODE,LOCATION_NAME,DATA_YEAR_x,AGENCY_ID,NIBRS_MONTH_ID,CARGO_THEFT_FLAG,SUBMISSION_DATE,INCIDENT_DATE,REPORT_DATE_FLAG,INCIDENT_HOUR,CLEARED_EXCEPT_ID,CLEARED_EXCEPT_DATE,INCIDENT_STATUS,DATA_HOME,ORIG_FORMAT,DID,YEARLY_AGENCY_ID,DATA_YEAR_y,ORI,LEGACY_ORI,COVERED_BY_LEGACY_ORI,DIRECT_CONTRIBUTOR_FLAG,DORMANT_FLAG,DORMANT_YEAR,REPORTING_TYPE,UCR_AGENCY_NAME,NCIC_AGENCY_NAME,PUB_AGENCY_NAME,PUB_AGENCY_UNIT,AGENCY_STATUS,STATE_ID,STATE_NAME,STATE_ABBR,STATE_POSTAL_ABBR,DIVISION_CODE,DIVISION_NAME,REGION_CODE,REGION_NAME,REGION_DESC,AGENCY_TYPE_NAME,POPULATION,SUBMITTING_AGENCY_ID,SAI,SUBMITTING_AGENCY_NAME,SUBURBAN_AREA_FLAG,POPULATION_GROUP_ID,POPULATION_GROUP_CODE,POPULATION_GROUP_DESC,PARENT_POP_GROUP_CODE,PARENT_POP_GROUP_DESC,MIP_FLAG,POP_SORT_ORDER,SUMMARY_RAPE_DEF,PE_REPORTED_FLAG,MALE_OFFICER,MALE_CIVILIAN,PED.MALE_OFFICER+PED.MALE_CIVILIAN,FEMALE_OFFICER,FEMALE_CIVILIAN,PED.FEMALE_CIVILIAN+PED.FEMALE_OFFICER,0,0.1,NIBRS_CERT_DATE,NIBRS_START_DATE,NIBRS_LEOKA_START_DATE,NIBRS_CT_START_DATE,NIBRS_MULTI_BIAS_START_DATE,NIBRS_OFF_ETH_START_DATE,COVERED_FLAG,COUNTY_NAME,MSA_NAME,PUBLISHABLE_FLAG,PARTICIPATED,NIBRS_PARTICIPATED,DATA_YEAR_x,WEAPON_ID,NIBRS_WEAPON_ID,WEAPON_CODE,WEAPON_NAME,SHR_FLAG,DATA_YEAR_y,OFFENDER_ID,OFFENDER_SEQ_NUM,AGE_ID_y,AGE_NUM_y,SEX_CODE_y,RACE_ID_y,ETHNICITY_ID_y,AGE_RANGE_LOW_NUM_y,AGE_RANGE_HIGH_NUM_y,RACE_ID,RACE_CODE,RACE_DESC,SORT_ORDER,START_YEAR,END_YEAR,NOTES
1358,2019,148954217.0,123115231,5,C,20,NaN,NaN,2019.0,38065366.0,1.0,29-SEP-19,1.0,C,5.0,5.0,17.0,M,1.0,2.0,NaN,H,NaN,17.0,0.0,O,On View,5,290,Destruction/Damage/Vandalism of Property,Property,N,Y,11.0,Destruction/Damage/Vandalism of Property,A,20,Residence/Home,2019,10092,10527991,NaN,13-APR-20,28-SEP-19,NaN,12.0,6,NaN,0,C,F,71082367,100922019,2019,MO1010500,MO1010500,NaN,N,N,NaN,I,SCOTT CITY,SCOTT CITY,Scott City,NaN,A,28,Missouri,MO,MO,4,West North Central,2,Midwest,Region II,City,4493,23376,MOUCR0001,Missouri State Highway Patrol UCR Program Offi...,N,10,6,"Cities from 2,500 thru 9,999",6,"Cities from 2,500 thru 9,999",N,2,R,Y,13.0,1.0,14.0,0.0,4.0,4.0,0,0,01-OCT-05,01-JUN-19,01-JUN-19,01-JUN-19,01-JUN-19,01-JUN-19,N,SCOTT,Non-MSA,Y,Y,Y,NaN,NaN,NaN,NaN,NaN,NaN,2019,140053399,1,5.0,17.0,M,1.0,2.0,17.0,0.0,1.0,W,White,10.0,NaN,NaN,NaN
1359,2019,148954219.0,123115231,16,C,13,NaN,NaN,2019.0,38065366.0,1.0,29-SEP-19,1.0,C,5.0,5.0,17.0,M,1.0,2.0,NaN,H,NaN,17.0,0.0,O,On View,16,35A,Drug/Narcotic Violations,Society,N,Y,NaN,Drug/Narcotic Offenses,A,13,Highway/Road/Alley/Street/Sidewalk,2019,10092,10527991,NaN,13-APR-20,28-SEP-19,NaN,12.0,6,NaN,0,C,F,71082367,100922019,2019,MO1010500,MO1010500,NaN,N,N,NaN,I,SCOTT CITY,SCOTT CITY,Scott City,NaN,A,28,Missouri,MO,MO,4,West North Central,2,Midwest,Region II,City,4493,23376,MOUCR0001,Missouri State Highway Patrol UCR Program Offi...,N,10,6,"Cities from 2,500 thru 9,999",6,"Cities from 2,500 thru 9,999",N,2,R,Y,13.0,1.0,14.0,0.0,4.0,4.0,0,0,01-OCT-05,01-JUN-19,01-JUN-19,01-JUN-19,01-JUN-19,01-JUN-19,N,SCOTT,Non-MSA,Y,Y,Y,NaN,NaN,NaN,NaN,NaN,NaN,2019,140053399,1,5.0,17.0,M,1.0,2.0,17.0,0.0,1.0,W,White,10.0,NaN,NaN,NaN
5216,2019,148314019.0,122587835,5,C,20,NaN,NaN,2019.0,37631978.0,1.0,10-AUG-19,3.0,C,5.0,5.0,37.0,F,1.0,2.0,NaN,NaN,NaN,37.0,0.0,T,Taken INTO Custody,5,290,Destruction/Damage/Vandalism of Property,Property,N,Y,11.0,Destruction/Damage/Vandalism of Property,A,20,Residence/Home,2019,10092,9961238,NaN,26-MAR-20,10-AUG-19,NaN,21.0,6,NaN,0,C,F,69873522,100922019,2019,MO1010500,MO1010500,NaN,N,N,NaN,I,SCOTT CITY,SCOTT CITY,Scott City,NaN,A,28,Missouri,MO,MO,4,West North Central,2,Midwest,Region II,City,4493,23376,MOUCR0001,Missouri State Highway Patrol UCR Program Offi...,N,10,6,"Cities from 2,500 thru 9,999",6,"Cities from 2,500 thru 9,999",N,2,R,Y,13.0,1.0,14.0,0.0,4.0,4.0,0,0,01-OCT-05,01-JUN-19,01-JUN-19,01-JUN-19,01-JUN-19,01-JUN-19,N,SCOTT,Non-MSA,Y,Y,Y,NaN,NaN,NaN,NaN,NaN,NaN,2019,139349603,1,5.0,37.0,F,1.0,2.0,37.0,0.0,1.0,W,White,10.0,NaN,NaN,NaN
21147,2019,143149361.0,118014786,35,C,11,NaN,NaN,2019.0,35968856.0,1.0,19-OCT-19,3.0,C,51.0,5.0,39.0,M,1.0,2.0,NaN,NaN,NaN,39.0,0.0,T,Taken INTO Custody,35,35B,Drug Equipment Violations,Society,N,Y,NaN,Drug/Narcotic Offenses,A,11,Government/Public Building,2019,10092,10749471,NaN,25-NOV-19,19-OCT-19,NaN,18.0,6,NaN,0,C,F,60723128,100922019,2019,MO1010500,MO1010500,NaN,N,N,NaN,I,SCOTT CITY,SCOTT CITY,Scott City,NaN,A,28,Missouri,MO,MO,4,West North Central,2,Midwest,Region II,City,4493,23376,MOUCR0001,Missouri State Highway Patrol UCR Program Offi...,N,10,6,"Cities from 2,500 thru 9,999",6,"Cities from 2,500 thru 9,999",N,2,R,Y,13.0,1.0,14.0,0.0,4.0,4.0,0,0,01-OCT-05,01-JUN-19,01-JUN-19,01-JUN-19,01-JUN-19,01-JUN-19,N,SCOTT,Non-MSA,Y,Y,Y,NaN,NaN,NaN,NaN,NaN,NaN,2019,134076231,1,5.0,39.0,M,1.0,2.0,39.0,0.0,1.0,W,White,10.0,NaN,NaN,NaN
21148,2019,143149360.0,118014786,16,C,11,NaN,NaN,2019.0,35968856.0,1.0,19-OCT-19,3.0,C,51.0,5.0,39.0,M,1.0,2.0,NaN,NaN,NaN,39.0,0.0,T,Taken INTO Custody,16,35A,Drug/Narcotic Violations,Society,N,Y,NaN,Drug/Narcotic Offenses,A,11,Government/Public Building,2019,10092,10749471,NaN,25-NOV-19,19-OCT-19,NaN,18.0,6,NaN,0,C,F,60723128,100922019,2019,MO1010500,MO1010500,NaN,N,N,NaN,I,SCOTT CITY,SCOTT CITY,Scott City,NaN,A,28,Missouri,MO,MO,4,West North Central,2,Midwest,Region II,City,4493,23376,MOUCR0001,Missouri State Highway Patrol UCR Program Offi...,N,10,6,"Cities from 2,500 thru 9,999",6,"Cities from 2,500 thru 9,999",N,2,R,Y,13.0,1.0,14.0,0.0,4.0,4.0,0,0,01-OCT-05,01-JUN-19,01-JUN-19,01-JUN-19,01-JUN-19,01-JUN-19,N,SCOTT,Non-MSA,Y,Y,Y,NaN,NaN,NaN,NaN,NaN,NaN,2019,134076231,1,5.0,39.0,M,1.0,2.0,39.0,0.0,1.0,W,White,10.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
169104,2019,148318383.0,122587895,16,C,13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16,35A,Drug/Narcotic Violations,Society,N,Y,NaN,Drug/Narcotic Offenses,A,13,Highway/Road/Alley/Street/Sidewalk,2019,10092,9961238,NaN,26-MAR-20,26-AUG-19,NaN,1.0,6,NaN,0,C,F,69873652,100922019,2019,MO1010500,MO1010500,NaN,N,N,NaN,I,SCOTT CITY,SCOTT CITY,Scott City,NaN,A,28,Missouri,MO,MO,4,West North Central,2,Midwest,Region II,City,4493,23376,MOUCR0001,Missouri State Highway Patrol UCR Program Offi...,N,10,6,"Cities from 2,500 thru 9,999",6,"Cities from 2,500 thru 9,999",N,2,R,Y,13.0,1.0,14.0,0.0,4.0,4.0,0,0,01-OCT-05,01-JUN-19,01-JUN-19,01-JUN-19,01-JUN-19,01-JUN-19,N,SCOTT,Non-MSA,Y,Y,Y,NaN,NaN,NaN,NaN,NaN,NaN,2019,139357344,1,5.0,25.0,M,1.0,2.0,25.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
169105,2019,148314090.0,122582010,16,C,13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16,35A,Drug/Narcotic Violations,Society,N,Y,NaN,Drug/Narcotic Offenses,A,13,Highway/Road/Alley/Street/Sidewalk,2019,10092,9134065,NaN,26-MAR-20,28-JUN-19,NaN,10.0,6,NaN,0,C,F,69873676,100922019,2019,MO1010500,MO1010500,NaN,N,N,NaN,I,SCOTT CITY,SCOTT CITY,Scott City,NaN,A,28,Missouri,MO,MO,4,West North Central,2,Midwest,Region II,City,4493,23376,MOUCR0001,Missouri State Highway Patrol UCR Program Offi...,N,10,6,"Cities from 2,500 thru 9,999",6,"Cities from 2,500 thru 9,999",N,2,R,Y,13.0,1.0,14.0,0.0,4.0,4.0,0,0,01-OCT-05,01-JUN-19,01-JUN-19,01-JUN-19,01-JUN-19,01-JUN-19,N,SCOTT,Non-MSA,Y,Y,Y,NaN,NaN,NaN,NaN,NaN,NaN,2019,139349675,1,5.0,24.0,M,1.0,2.0,24.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
169110,2019,148314136.0,122587946,35,C,13,NaN,NaN,2019.0,37635634.0,1.0,26-JUL-19,3.0,N,16.0,5.0,48.0,F,1.0,2.0,NaN,NaN,NaN,48.0,0.0,T,Taken INTO Custody,35,35B,Drug Equipment Violations,Society,N,Y,NaN,Drug/Narcotic Offenses,A,13,Highway/Road/Alley/Street/Sidewalk,2019,10092,9191063,NaN,26-MAR-20,26-JUL-19,NaN,13.0,6,NaN,0,C,F,69877427,100922019,2019,MO1010500,MO1010500,NaN,N,N,NaN,I,SCOTT CITY,SCOTT CITY,Scott City,NaN,A,28,Missouri,MO,MO,4,West North Central,2,Midwest,Region II,City,4493,23376,MOUCR0001,Missouri State Highway Patrol UCR Program Offi...,N,10,6,"Cities from 2,500 thru 9,999",6,"Cities from 2,500 thru 9,999",N,2,R,Y,13.0,1.0,14.0,0.0,4.0,4.0,0,0,01-OCT-05,01-JUN-19,01-JUN-19,01-JUN-19,01-JUN-19,01-JUN-19,N,SCOTT,Non-MSA,Y,Y,Y,NaN,NaN,NaN,NaN,NaN,NaN,2019,139367084,1,5.0,48.0,F,1.0,2.0,48.0,0.0,1.0,W,White,10.0,NaN,NaN,NaN
169111,2019,148314135.0,122587946,16,C,13,NaN,NaN,2019.0,37635634.0,1.0,26-JUL-19,3.0,N,16.0,5.0,48.0,F,1.0,2.0,NaN,NaN,NaN,48.0,0.0,T,Taken INTO Custody,16,35A,Drug/Narcotic Violations,Society,N,Y,NaN,Drug/Narcotic Offenses,A,13,Highway/Road/Alley/Street/Sidewalk,2019,10092,9191063,NaN,26-MAR-20,26-JUL-19,NaN,13.0,6,NaN,0,C,F,69877427,100922019,2019,MO1010500,MO1010500,NaN,N,N,NaN,I,SCOTT CITY,SCOTT CITY,Scott City,NaN,A,28,Missouri,MO,MO,4,West North Central,2,Midwest,Region II,City,4493,23376,MOUCR0001,Missouri State Highway Patrol UCR Program Offi...,N,10,6,"Cities from 2,500 thru 9,999",6,"Cities from 2,500 thru 9,999",N,2,R,Y,13.0,1.0,14.0,0.0,4.0,4.0,0,0,01-OCT-05,01-JUN-19,01-JUN-19,01-JUN-19,01-JUN-19,01-JUN-19,N,SCOTT,Non-MSA,Y,Y,Y,NaN,NaN,NaN,NaN,NaN,NaN,2019,139367084,1,5.0,48.0,F,1.0,2.0,48.0,0.0,1.0,W,White,10.0,NaN,NaN,NaN
170282,2019,148314005.0,122587814,16,C,20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16,35A,Drug/Narcotic Violations,Society,N,Y,NaN,Drug/Narcotic Offenses,A,20,Residence/Home,2019,10092,10527991,NaN,26-MAR-20,07-SEP-19,NaN,13.0,6,NaN,0,C,F,69877185,100922019,2019,MO1010500,MO1010500,NaN,N,N,NaN,I,SCOTT CITY,SCOTT CITY,Scott City,NaN,A,28,Missouri,MO,MO,4,West North Central,2,Midwest,Region II,City,4493,23376,MOUCR0001,Missouri State Highway Patrol UCR Program Offi...,N,10,6,"Cities from 2,500 thru 9,999",6,"Cities from 2,500 thru 9,999",N,2,R,Y,13.0,1.0,14.0,0.0,4.0,4.0,0,0,01-OCT-05,01-JUN-19,01-JUN-19,01-JUN-19,01-JUN-19,01-JUN-19,N,SCOTT,Non-MSA,Y,Y,Y,NaN,NaN,NaN,NaN,NaN,NaN,2019,139349593,1,5.0,55.0,M,1.0,2.0,55.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [51]:
ScottCOViz = ScottCO[['RACE_DESC','OFFENSE_NAME']]

In [52]:
alt.Chart(ScottCOViz).mark_bar().encode(
    x=alt.X('count(RACE_DESC)'),
    y=alt.Y('OFFENSE_NAME'),
    color=alt.Color('OFFENSE_NAME:N',scale=alt.Scale(scheme='category20c'))
)

alt.Chart(...)

In [53]:
ScottCO['OFFENSE_NAME'].count()

236

In [54]:
ScottCOViz1 = ScottCO[['OFFENSE_ID','LOCATION_NAME','OFFENSE_NAME']]

In [55]:
alt.Chart(ScottCOViz1).mark_bar().encode(
    x=alt.X('count(OFFENSE_ID)', stack="normalize",axis=alt.Axis(format='%')),
    y='LOCATION_NAME:N',
    color=alt.Color('OFFENSE_NAME:N',scale=alt.Scale(scheme='category20c'))
)

alt.Chart(...)

In [56]:
ScottCOViz2 = ScottCO[['OFFENSE_ID','OFFENSE_NAME','WEAPON_ID']]

In [57]:
alt.Chart(ScottCOViz2).mark_bar().encode(
    x=alt.X('count(OFFENSE_ID)', stack="normalize",axis=alt.Axis(format='%')),
    y='OFFENSE_NAME:N',
    color=alt.Color('WEAPON_ID:N',scale=alt.Scale(scheme='category20c'))
)

alt.Chart(...)

In [58]:
ScottCODrugOffenses = ScottCO[ScottCO['OFFENSE_NAME'].isin(['Drug/Narcotic Violations','Drug Equipment Violations'])]

In [59]:
# pd.set_option('display.max_columns', None)

In [60]:
ScottCODrugOffenses.columns.values

array(['DATA_YEAR_x', 'OFFENSE_ID', 'INCIDENT_ID', 'OFFENSE_TYPE_ID_x',
       'ATTEMPT_COMPLETE_FLAG', 'LOCATION_ID', 'NUM_PREMISES_ENTERED',
       'METHOD_ENTRY_CODE', 'DATA_YEAR_y', 'ARRESTEE_ID',
       'ARRESTEE_SEQ_NUM', 'ARREST_DATE', 'ARREST_TYPE_ID',
       'MULTIPLE_INDICATOR', 'OFFENSE_TYPE_ID_y', 'AGE_ID_x', 'AGE_NUM_x',
       'SEX_CODE_x', 'RACE_ID_x', 'ETHNICITY_ID_x', 'RESIDENT_CODE',
       'UNDER_18_DISPOSITION_CODE', 'CLEARANCE_IND',
       'AGE_RANGE_LOW_NUM_x', 'AGE_RANGE_HIGH_NUM_x', 'ARREST_TYPE_CODE',
       'ARREST_TYPE_NAME', 'OFFENSE_TYPE_ID', 'OFFENSE_CODE',
       'OFFENSE_NAME', 'CRIME_AGAINST', 'CT_FLAG', 'HC_FLAG', 'HC_CODE',
       'OFFENSE_CATEGORY_NAME', 'OFFENSE_GROUP', 'LOCATION_CODE',
       'LOCATION_NAME', 'DATA_YEAR_x', 'AGENCY_ID', 'NIBRS_MONTH_ID',
       'CARGO_THEFT_FLAG', 'SUBMISSION_DATE', 'INCIDENT_DATE',
       'REPORT_DATE_FLAG', 'INCIDENT_HOUR', 'CLEARED_EXCEPT_ID',
       'CLEARED_EXCEPT_DATE', 'INCIDENT_STATUS', 'DATA_HOME',
       'ORIG_FORMAT', 'DID', 'YEARLY_AGENCY_ID', 'DATA_YEAR_y', 'ORI',
       'LEGACY_ORI', 'COVERED_BY_LEGACY_ORI', 'DIRECT_CONTRIBUTOR_FLAG',
       'DORMANT_FLAG', 'DORMANT_YEAR', 'REPORTING_TYPE',
       'UCR_AGENCY_NAME', 'NCIC_AGENCY_NAME', 'PUB_AGENCY_NAME',
       'PUB_AGENCY_UNIT', 'AGENCY_STATUS', 'STATE_ID', 'STATE_NAME',
       'STATE_ABBR', 'STATE_POSTAL_ABBR', 'DIVISION_CODE',
       'DIVISION_NAME', 'REGION_CODE', 'REGION_NAME', 'REGION_DESC',
       'AGENCY_TYPE_NAME', 'POPULATION', 'SUBMITTING_AGENCY_ID', 'SAI',
       'SUBMITTING_AGENCY_NAME', 'SUBURBAN_AREA_FLAG',
       'POPULATION_GROUP_ID', 'POPULATION_GROUP_CODE',
       'POPULATION_GROUP_DESC', 'PARENT_POP_GROUP_CODE',
       'PARENT_POP_GROUP_DESC', 'MIP_FLAG', 'POP_SORT_ORDER',
       'SUMMARY_RAPE_DEF', 'PE_REPORTED_FLAG', 'MALE_OFFICER',
       'MALE_CIVILIAN', 'PED.MALE_OFFICER+PED.MALE_CIVILIAN',
       'FEMALE_OFFICER', 'FEMALE_CIVILIAN',
       'PED.FEMALE_CIVILIAN+PED.FEMALE_OFFICER', '0', '0.1',
       'NIBRS_CERT_DATE', 'NIBRS_START_DATE', 'NIBRS_LEOKA_START_DATE',
       'NIBRS_CT_START_DATE', 'NIBRS_MULTI_BIAS_START_DATE',
       'NIBRS_OFF_ETH_START_DATE', 'COVERED_FLAG', 'COUNTY_NAME',
       'MSA_NAME', 'PUBLISHABLE_FLAG', 'PARTICIPATED',
       'NIBRS_PARTICIPATED', 'DATA_YEAR_x', 'WEAPON_ID',
       'NIBRS_WEAPON_ID', 'WEAPON_CODE', 'WEAPON_NAME', 'SHR_FLAG',
       'DATA_YEAR_y', 'OFFENDER_ID', 'OFFENDER_SEQ_NUM', 'AGE_ID_y',
       'AGE_NUM_y', 'SEX_CODE_y', 'RACE_ID_y', 'ETHNICITY_ID_y',
       'AGE_RANGE_LOW_NUM_y', 'AGE_RANGE_HIGH_NUM_y', 'RACE_ID',
       'RACE_CODE', 'RACE_DESC', 'SORT_ORDER', 'START_YEAR', 'END_YEAR',
       'NOTES'], dtype=object)

In [61]:
ScottCODrugOffenses.WEAPON_ID.notnull().any()

False

In [62]:
ScottCODrugOffensesViz1 = ScottCODrugOffenses[['OFFENSE_ID','LOCATION_NAME','NIBRS_WEAPON_ID']]

In [63]:
alt.Chart(ScottCODrugOffensesViz1).mark_bar().encode(
    x=alt.X('count(OFFENSE_ID)'),
    y='LOCATION_NAME:N'
)

alt.Chart(...)

In [64]:
ScottCODrugOffensesViz1

         OFFENSE_ID                       LOCATION_NAME  NIBRS_WEAPON_ID
1359    148954219.0  Highway/Road/Alley/Street/Sidewalk              NaN
21147   143149361.0          Government/Public Building              NaN
21148   143149360.0          Government/Public Building              NaN
21152   143158269.0             Parking/Drop Lot/Garage              NaN
21153   143158269.0             Parking/Drop Lot/Garage              NaN
...             ...                                 ...              ...
169104  148318383.0  Highway/Road/Alley/Street/Sidewalk              NaN
169105  148314090.0  Highway/Road/Alley/Street/Sidewalk              NaN
169110  148314136.0  Highway/Road/Alley/Street/Sidewalk              NaN
169111  148314135.0  Highway/Road/Alley/Street/Sidewalk              NaN
170282  148314005.0                      Residence/Home              NaN

[219 rows x 3 columns]

# Kansas City Drilldown

In [65]:
##Contact Jason Kander Campaign##

In [66]:
KC = MO2019Offenses[MO2019Offenses['PUB_AGENCY_NAME']=='Kansas City']

In [67]:
KC = KC[KC['OFFENSE_NAME'].isin(STAR_relevant_offenses)]

In [68]:
KC = KC[KC['WEAPON_ID'].isnull()]

In [69]:
KC['OFFENSE_NAME'].count()

7396

In [70]:
KC.groupby(['OFFENSE_NAME','RACE_DESC'])['OFFENSE_NAME'].count()
#incredibly disproportionate effect on blacks

OFFENSE_NAME                              RACE_DESC
Destruction/Damage/Vandalism of Property  American Indian or Alaska Native               1
                                          Asian                                          2
                                          Black or African American                    415
                                          Unknown                                        2
                                          White                                        255
Drug Equipment Violations                 Black or African American                    243
                                          Unknown                                        2
                                          White                                        410
Drug/Narcotic Violations                  American Indian or Alaska Native               2
                                          Asian                                          3
                                          Black or African American                    564
                                          Native Hawaiian or Other Pacific Islander      1
                                          Unknown                                        9
                                          White                                        609
Name: OFFENSE_NAME, dtype: int64

In [71]:
KC['ARREST_TYPE_ID'] = KC['ARREST_TYPE_ID'].fillna(0)
KC['ARREST_TYPE_ID']

272       0.0
274       2.0
278       0.0
283       0.0
284       0.0
         ...
168448    1.0
168450    0.0
168621    1.0
170291    0.0
170296    2.0
Name: ARREST_TYPE_ID, Length: 7396, dtype: float64

In [72]:
KC.groupby(['OFFENSE_NAME','RACE_DESC','ARREST_TYPE_ID'])['OFFENSE_NAME'].count()

OFFENSE_NAME                              RACE_DESC                                  ARREST_TYPE_ID
Destruction/Damage/Vandalism of Property  American Indian or Alaska Native           2.0                 1
                                          Asian                                      3.0                 2
                                          Black or African American                  1.0               115
                                                                                     2.0               192
                                                                                     3.0               108
                                          Unknown                                    2.0                 2
                                          White                                      1.0                81
                                                                                     2.0               105
                                                                                     3.0                69
Drug Equipment Violations                 Black or African American                  1.0                98
                                                                                     2.0                40
                                                                                     3.0               105
                                          Unknown                                    3.0                 2
                                          White                                      1.0               230
                                                                                     2.0                55
                                                                                     3.0               125
Drug/Narcotic Violations                  American Indian or Alaska Native           3.0                 2
                                          Asian                                      1.0                 2
                                                                                     3.0                 1
                                          Black or African American                  1.0               219
                                                                                     2.0               153
                                                                                     3.0               192
                                          Native Hawaiian or Other Pacific Islander  2.0                 1
                                          Unknown                                    2.0                 9
                                          White                                      1.0               302
                                                                                     2.0               125
                                                                                     3.0               182
Name: OFFENSE_NAME, dtype: int64

# 8th Congressional District Drilldown

In [73]:
EighthCongressionalCounties = ['Bollinger','Butler','Cape Girardeau','Carter','Crawford','Dent','Douglas','Dunklin',
'Howell','Iron','Jefferson','Madison','Mississippi','New Madrid','Oregon','Ozark','Pemiscot','Perry','Phelps',
'Reynolds','Ripley','Scott','Shannon','St. Francois','Ste. Genevieve','Stoddard','Texas','Washington','Wayne','Wright']

In [74]:
EighthCongressionalCounties = [county.upper() for county in EighthCongressionalCounties]

In [75]:
EighthCongressionalCounties = [county.replace('.','') for county in EighthCongressionalCounties]

In [76]:
EighthCongressionalCounties

['BOLLINGER',
 'BUTLER',
 'CAPE GIRARDEAU',
 'CARTER',
 'CRAWFORD',
 'DENT',
 'DOUGLAS',
 'DUNKLIN',
 'HOWELL',
 'IRON',
 'JEFFERSON',
 'MADISON',
 'MISSISSIPPI',
 'NEW MADRID',
 'OREGON',
 'OZARK',
 'PEMISCOT',
 'PERRY',
 'PHELPS',
 'REYNOLDS',
 'RIPLEY',
 'SCOTT',
 'SHANNON',
 'ST FRANCOIS',
 'STE GENEVIEVE',
 'STODDARD',
 'TEXAS',
 'WASHINGTON',
 'WAYNE',
 'WRIGHT']

In [77]:
EightCongressionalOffenses = MO2019Offenses[MO2019Offenses['COUNTY_NAME'].isin(EighthCongressionalCounties)]

In [78]:
EightCongressionalOffenses.columns.values

array(['DATA_YEAR_x', 'OFFENSE_ID', 'INCIDENT_ID', 'OFFENSE_TYPE_ID_x',
       'ATTEMPT_COMPLETE_FLAG', 'LOCATION_ID', 'NUM_PREMISES_ENTERED',
       'METHOD_ENTRY_CODE', 'DATA_YEAR_y', 'ARRESTEE_ID',
       'ARRESTEE_SEQ_NUM', 'ARREST_DATE', 'ARREST_TYPE_ID',
       'MULTIPLE_INDICATOR', 'OFFENSE_TYPE_ID_y', 'AGE_ID_x', 'AGE_NUM_x',
       'SEX_CODE_x', 'RACE_ID_x', 'ETHNICITY_ID_x', 'RESIDENT_CODE',
       'UNDER_18_DISPOSITION_CODE', 'CLEARANCE_IND',
       'AGE_RANGE_LOW_NUM_x', 'AGE_RANGE_HIGH_NUM_x', 'ARREST_TYPE_CODE',
       'ARREST_TYPE_NAME', 'OFFENSE_TYPE_ID', 'OFFENSE_CODE',
       'OFFENSE_NAME', 'CRIME_AGAINST', 'CT_FLAG', 'HC_FLAG', 'HC_CODE',
       'OFFENSE_CATEGORY_NAME', 'OFFENSE_GROUP', 'LOCATION_CODE',
       'LOCATION_NAME', 'DATA_YEAR_x', 'AGENCY_ID', 'NIBRS_MONTH_ID',
       'CARGO_THEFT_FLAG', 'SUBMISSION_DATE', 'INCIDENT_DATE',
       'REPORT_DATE_FLAG', 'INCIDENT_HOUR', 'CLEARED_EXCEPT_ID',
       'CLEARED_EXCEPT_DATE', 'INCIDENT_STATUS', 'DATA_HOME',
       'ORIG_FORMAT', 'DID', 'YEARLY_AGENCY_ID', 'DATA_YEAR_y', 'ORI',
       'LEGACY_ORI', 'COVERED_BY_LEGACY_ORI', 'DIRECT_CONTRIBUTOR_FLAG',
       'DORMANT_FLAG', 'DORMANT_YEAR', 'REPORTING_TYPE',
       'UCR_AGENCY_NAME', 'NCIC_AGENCY_NAME', 'PUB_AGENCY_NAME',
       'PUB_AGENCY_UNIT', 'AGENCY_STATUS', 'STATE_ID', 'STATE_NAME',
       'STATE_ABBR', 'STATE_POSTAL_ABBR', 'DIVISION_CODE',
       'DIVISION_NAME', 'REGION_CODE', 'REGION_NAME', 'REGION_DESC',
       'AGENCY_TYPE_NAME', 'POPULATION', 'SUBMITTING_AGENCY_ID', 'SAI',
       'SUBMITTING_AGENCY_NAME', 'SUBURBAN_AREA_FLAG',
       'POPULATION_GROUP_ID', 'POPULATION_GROUP_CODE',
       'POPULATION_GROUP_DESC', 'PARENT_POP_GROUP_CODE',
       'PARENT_POP_GROUP_DESC', 'MIP_FLAG', 'POP_SORT_ORDER',
       'SUMMARY_RAPE_DEF', 'PE_REPORTED_FLAG', 'MALE_OFFICER',
       'MALE_CIVILIAN', 'PED.MALE_OFFICER+PED.MALE_CIVILIAN',
       'FEMALE_OFFICER', 'FEMALE_CIVILIAN',
       'PED.FEMALE_CIVILIAN+PED.FEMALE_OFFICER', '0', '0.1',
       'NIBRS_CERT_DATE', 'NIBRS_START_DATE', 'NIBRS_LEOKA_START_DATE',
       'NIBRS_CT_START_DATE', 'NIBRS_MULTI_BIAS_START_DATE',
       'NIBRS_OFF_ETH_START_DATE', 'COVERED_FLAG', 'COUNTY_NAME',
       'MSA_NAME', 'PUBLISHABLE_FLAG', 'PARTICIPATED',
       'NIBRS_PARTICIPATED', 'DATA_YEAR_x', 'WEAPON_ID',
       'NIBRS_WEAPON_ID', 'WEAPON_CODE', 'WEAPON_NAME', 'SHR_FLAG',
       'DATA_YEAR_y', 'OFFENDER_ID', 'OFFENDER_SEQ_NUM', 'AGE_ID_y',
       'AGE_NUM_y', 'SEX_CODE_y', 'RACE_ID_y', 'ETHNICITY_ID_y',
       'AGE_RANGE_LOW_NUM_y', 'AGE_RANGE_HIGH_NUM_y', 'RACE_ID',
       'RACE_CODE', 'RACE_DESC', 'SORT_ORDER', 'START_YEAR', 'END_YEAR',
       'NOTES'], dtype=object)

In [79]:
EightCongressionalOffensesViz1 = EightCongressionalOffenses[['OFFENSE_ID','LOCATION_NAME','OFFENSE_NAME']]

In [80]:
alt.Chart(EightCongressionalOffensesViz1).mark_bar().encode(
    x=alt.X('count(OFFENSE_ID)', stack="normalize",axis=alt.Axis(format='%')),
    y='LOCATION_NAME:N',
    color=alt.Color('OFFENSE_NAME:N',scale=alt.Scale(scheme='category20c'))
)

MaxRowsError: The number of rows in your dataset is greater than the maximum allowed (5000). For information on how to plot larger datasets in Altair, see the documentation

alt.Chart(...)

In [81]:
EightCongressionalOffensesViz2 = EightCongressionalOffenses[['OFFENSE_ID','OFFENSE_NAME','WEAPON_NAME','COUNTY_NAME']]

In [82]:
alt.Chart(EightCongressionalOffensesViz2).mark_bar().encode(
    x=alt.X('count(OFFENSE_ID)', stack="normalize",axis=alt.Axis(format='%')),
    y='OFFENSE_NAME:N',
    color=alt.Color('WEAPON_NAME:N',scale=alt.Scale(scheme='category20c'))
)

MaxRowsError: The number of rows in your dataset is greater than the maximum allowed (5000). For information on how to plot larger datasets in Altair, see the documentation

alt.Chart(...)

In [83]:
EightCongressionalDrugOffenses = EightCongressionalOffenses[EightCongressionalOffenses['OFFENSE_NAME'].isin(['Drug/Narcotic Violations','Drug Equipment Violations'])]

In [84]:
EightCongressionalOffensesViz3 = EightCongressionalDrugOffenses[['OFFENSE_ID','LOCATION_NAME','COUNTY_NAME']]

In [85]:
alt.Chart(EightCongressionalOffensesViz3).mark_bar().encode(
    x=alt.X('count(OFFENSE_ID)'),
    y='COUNTY_NAME:N',
    color=alt.Color('LOCATION_NAME:N',scale=alt.Scale(scheme='category20c'))
)

alt.Chart(...)

In [86]:
EightCongressionalOffensesViz4 = EightCongressionalDrugOffenses[['ARRESTEE_ID','ARREST_TYPE_NAME','COUNTY_NAME','WEAPON_NAME']]

In [87]:
alt.Chart(EightCongressionalOffensesViz4).mark_bar().encode(
    x=alt.X('count(ARRESTEE_ID)'),
    y='ARREST_TYPE_NAME:N',
    color=alt.Color('WEAPON_NAME:N',scale=alt.Scale(scheme='category20c'))
)

alt.Chart(...)

In [88]:
EightCongressionalOffensesViz5 = EightCongressionalDrugOffenses[['ARRESTEE_ID','RACE_DESC','COUNTY_NAME']]

In [89]:
alt.Chart(EightCongressionalOffensesViz5).mark_bar().encode(
    x=alt.X('count(ARRESTEE_ID)'),
    y='RACE_DESC:N',
)

alt.Chart(...)

In [90]:
DrugPossession = pd.read_csv('arrests-for-drug-possession-offenses-2019.csv')

In [91]:
Participation = pd.read_csv('mo-participation-data.csv')

In [92]:
CrimesAgainstSociety = pd.read_csv('arrests-for-crimes-against-society-offenses-2019.csv')

In [93]:
AllArrests = pd.read_csv('all-arrest-by-offense-2019.csv')

In [94]:
Prostitution = pd.read_csv('arrests-for-prostitution-violations-2019.csv')

In [95]:
Gambling = pd.read_csv('arrests-for-gambling-offenses-2019.csv')

In [96]:
DrugMeasureType = pd.read_csv('NIBRS_DRUG_MEASURE_TYPE.csv')

In [97]:
# import geopandas as gpd

In [98]:
# def get_gpd_df(use_shape_file=True):
#     if use_shape_file:
#         gdf = gpd.read_file(shape_file_loc)
#     else:
#         toronto_json = open_geojson()
#         gdf = gpd.GeoDataFrame.from_features((toronto_json))
#     return gdf

In [99]:
MOCountiesShape = pd.read_csv('Missouri_Counties.csv')

In [100]:
MOCountiesShape

,OBJECTID,COUNTYNAME,COUNTYFIPS,COUNTYGNIS,NAME_UCASE,POP_1990,POP_2000,ACRES,SQ_MILES,CNTY_SEAT,CO_CLASS,ShapeSTArea,ShapeSTLength
0,1,Clark,45,758477,CLARK,7547,7416,327632.419997,511.925656,Kahoka,3,1.325887e+09,164046.437172
1,2,Atchison,5,758457,ATCHISON,7457,6430,351990.513001,549.985177,Rock Port,3,1.424485e+09,183529.686005
2,3,Scotland,199,758552,SCOTLAND,4822,4983,280948.966704,438.982760,Memphis,3,1.136968e+09,135147.562405
3,4,Schuyler,197,758551,SCHUYLER,4236,4170,197084.747448,307.944918,Lancaster,3,7.975771e+08,156174.553037
4,5,Nodaway,147,758528,NODAWAY,21709,21912,561734.052590,877.709457,Maryville,3,2.273255e+09,212568.360652
...,...,...,...,...,...,...,...,...,...,...,...,...,...
110,111,McDonald,119,758518,MCDONALD,16938,21681,345102.871821,539.223237,Pineville,3,1.396929e+09,155042.255480
111,112,Dunklin,69,758489,DUNKLIN,33112,33155,350410.474198,547.516366,Kennett,3,1.418415e+09,274321.961664
112,113,Pemiscot,155,758532,PEMISCOT,21921,20047,326247.923468,509.762380,Caruthersville,3,1.320522e+09,189371.277913
113,114,Marion,127,758517,MARION,27682,28289,284331.719607,444.268312,Palmyra,3,1.150632e+09,152114.138426
114,115,Monroe,137,758523,MONROE,9104,9311,428556.385958,669.619353,Paris,3,1.734337e+09,172133.702469

In [101]:
d = {'911 Operator Flag': [.418], 'Independent Request': [.348], 'STAR self-initiation': [.234]}
STARAssignments = pd.DataFrame(data=d).T

In [102]:
STARAssignments.columns = ['Percentage']

In [103]:
STARAssignments = STARAssignments.reset_index()

In [104]:
STARAssignments.columns = ['Type','Percentage']

In [105]:
alt.Chart(STARAssignments).mark_bar().encode(
    x=alt.X('Percentage',axis=alt.Axis(format='%'),title='Percentage of Calls'),
    y=alt.Y('Type',title=None),
    color = alt.Color('Percentage',legend=None)
).configure(font='Merriweather'
).configure_axis(labelFontSize=15,titleFontSize=24
).properties(
    width=500,
    height=200
)

alt.Chart(...)

In [106]:
#median star 24.65 on scene personnel time
#median traditional 34.08
d = {'STAR': [24.65], 'Traditional': [34.08]}
ResponseCallTime = pd.DataFrame(data=d).T.reset_index()
ResponseCallTime

         index      0
0         STAR  24.65
1  Traditional  34.08

In [107]:
ResponseCallTime.columns = ['Type','MedianResponseTime']

In [108]:
alt.Chart(ResponseCallTime).mark_bar().encode(
    x=alt.X('MedianResponseTime',title='Median Response Time (in minutes)',axis=alt.Axis(values=[0, 5, 10, 15, 20, 25, 30, 35])),
    y=alt.Y('Type',title=None),
    color = alt.Color('MedianResponseTime',legend=None)
).configure(font='Merriweather'
).configure_axis(labelFontSize=15,titleFontSize=24,grid=False
).properties(
    width=500,
    height=200
)

alt.Chart(...)

In [109]:
d = {'Homeless Services': [30], 'Walk-in Crisis Center': [24], 'Hospital': [18]}
Transportation = pd.DataFrame(data=d).T.reset_index()
Transportation.columns = ['Location','Times']
Transportation

                Location  Times
0      Homeless Services     30
1  Walk-in Crisis Center     24
2               Hospital     18

In [110]:
alt.Chart(Transportation).mark_bar().encode(
    x=alt.X('Times',title='Frequency of Transportation'),#,axis=alt.Axis(values=[0, 5, 10, 15, 20, 25, 30, 35])),
    y=alt.Y('Location',title=None),
    color = alt.Color('Location',legend=None)
).configure(font='Merriweather'
).configure_axis(labelFontSize=15,titleFontSize=24,grid=False
).properties(
    width=500,
    height=200
)

alt.Chart(...)

In [132]:
denverCrime = pd.read_csv('DENVERcrime.csv')

In [133]:
denverCrime

,INCIDENT_ID,OFFENSE_ID,OFFENSE_CODE,OFFENSE_CODE_EXTENSION,OFFENSE_TYPE_ID,OFFENSE_CATEGORY_ID,FIRST_OCCURRENCE_DATE,LAST_OCCURRENCE_DATE,REPORTED_DATE,INCIDENT_ADDRESS,GEO_X,GEO_Y,GEO_LON,GEO_LAT,DISTRICT_ID,PRECINCT_ID,NEIGHBORHOOD_ID,IS_CRIME,IS_TRAFFIC
0,2021224206,2021224206220200,2202,0,burglary-residence-by-force,burglary,4/18/2021 10:30:00 PM,4/19/2021 5:00:00 AM,4/21/2021 3:25:00 PM,300 W 11TH AVE,3142828.0,1692472.0,-104.992161,39.733543,6.0,611.0,civic-center,1,0
1,2021225308,2021225308240400,2404,0,theft-of-motor-vehicle,auto-theft,4/21/2021 11:25:00 PM,NaN,4/22/2021 12:01:00 AM,5700 BLK W DARTMOUTH AVE,3124936.0,1664570.0,-105.056261,39.657203,4.0,423.0,bear-valley,1,0
2,20216009452,20216009452239900,2399,0,theft-other,larceny,3/22/2021 12:51:00 PM,3/22/2021 12:51:00 PM,4/21/2021 10:13:00 PM,3412 N HUMBOLDT ST,3149191.0,1703917.0,-104.969299,39.764862,2.0,211.0,cole,1,0
3,20216009439,20216009439230500,2305,0,theft-items-from-vehicle,theft-from-motor-vehicle,4/21/2021 12:00:00 PM,4/21/2021 12:05:00 PM,4/21/2021 1:17:00 PM,1900 BLK S CLARKSON ST,3146781.0,1673727.0,-104.978488,39.682023,3.0,313.0,platt-park,1,0
4,20218017976,20218017976240400,2404,0,theft-of-motor-vehicle,auto-theft,3/9/2021 12:01:00 PM,4/21/2021 12:20:00 PM,4/21/2021 12:20:00 PM,24050 E 78TH AVE,3223419.0,1730557.0,-104.704438,39.836504,7.0,759.0,dia,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
480103,2021145230,2021145230240400,2404,0,theft-of-motor-vehicle,auto-theft,3/12/2021 3:00:00 AM,3/12/2021 6:00:00 AM,3/12/2021 6:06:00 AM,1100 BLK N GALAPAGO ST,3141647.0,1693035.0,-104.996349,39.735107,1.0,123.0,lincoln-park,1,0
480104,2021146155,2021146155220300,2203,0,burglary-business-by-force,burglary,3/10/2021 9:00:00 PM,3/11/2021 8:00:00 AM,3/12/2021 4:04:00 PM,17900 E 56TH AVE,3202807.0,1716160.0,-104.778238,39.797456,5.0,522.0,gateway-green-valley-ranch,1,0
480105,2021145594,2021145594131501,1315,1,aggravated-assault-dv,aggravated-assault,3/12/2021 10:15:00 AM,NaN,3/12/2021 11:13:00 AM,2140 S DELAWARE ST,3142957.0,1672196.0,-104.992105,39.677879,3.0,313.0,overland,1,0
480106,2021146785,2021146785131502,1315,2,menacing-felony-w-weap,aggravated-assault,3/12/2021 8:20:00 PM,NaN,3/12/2021 8:20:00 PM,1088 S BRYANT ST,3135704.0,1679185.0,-105.017741,39.697174,4.0,412.0,athmar-park,1,0
480107,2021146095,2021146095240400,2404,0,theft-of-motor-vehicle,auto-theft,3/11/2021 5:00:00 PM,3/12/2021 10:00:00 AM,3/12/2021 2:43:00 PM,3257 S PARKER RD,3183194.0,1665052.0,-104.849338,39.657563,3.0,323.0,kennedy,1,0

In [112]:
denverCrime[['OFFENSE_CODE','OFFENSE_TYPE_ID']].drop_duplicates().sort_values('OFFENSE_TYPE_ID')

        OFFENSE_CODE                OFFENSE_TYPE_ID
5077            7399  accessory-conspiracy-to-crime
235             1311         agg-aslt-police-weapon
126             1315             aggravated-assault
11              1315          aggravated-assault-dv
277352          2503            altering-vin-number
...              ...                            ...
896             5212  weapon-poss-illegal-dangerous
223             5213   weapon-unlawful-discharge-of
254055          5214           weapon-unlawful-sale
7221            3611                 window-peeping
105689          5799                    wiretapping

[200 rows x 2 columns]

In [113]:
coloradoOffenses = pd.read_csv('CO_2019_NIBRS_OFFENSE.csv')

In [114]:
coloradoOffenses = coloradoOffenses.merge(OffenseTypes,how='left',on='OFFENSE_TYPE_ID')

In [115]:
coloradoOffenses

,DATA_YEAR,OFFENSE_ID,INCIDENT_ID,OFFENSE_TYPE_ID,ATTEMPT_COMPLETE_FLAG,LOCATION_ID,NUM_PREMISES_ENTERED,METHOD_ENTRY_CODE,OFFENSE_CODE,OFFENSE_NAME,CRIME_AGAINST,CT_FLAG,HC_FLAG,HC_CODE,OFFENSE_CATEGORY_NAME,OFFENSE_GROUP
0,2019,139343580,114122664,7,C,20,NaN,NaN,23G,Theft of Motor Vehicle Parts or Accessories,Property,N,N,NaN,Larceny/Theft Offenses,A
1,2019,139339591,114122668,45,C,20,NaN,NaN,23H,All Other Larceny,Property,Y,N,NaN,Larceny/Theft Offenses,A
2,2019,139339603,114114683,21,C,13,NaN,NaN,240,Motor Vehicle Theft,Property,Y,Y,7.0,Motor Vehicle Theft,A
3,2019,139339607,114122695,45,C,23,NaN,NaN,23H,All Other Larceny,Property,Y,N,NaN,Larceny/Theft Offenses,A
4,2019,139339608,114122697,23,C,12,NaN,NaN,23C,Shoplifting,Property,N,N,NaN,Larceny/Theft Offenses,A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
305311,2019,141844716,116813642,5,C,18,NaN,NaN,290,Destruction/Damage/Vandalism of Property,Property,N,Y,11.0,Destruction/Damage/Vandalism of Property,A
305312,2019,141852632,116813645,35,C,8,NaN,NaN,35B,Drug Equipment Violations,Society,N,Y,NaN,Drug/Narcotic Offenses,A
305313,2019,141848922,116813645,16,C,8,NaN,NaN,35A,Drug/Narcotic Violations,Society,N,Y,NaN,Drug/Narcotic Offenses,A
305314,2019,141844745,116813666,16,C,38,NaN,NaN,35A,Drug/Narcotic Violations,Society,N,Y,NaN,Drug/Narcotic Offenses,A
305315,2019,141848949,116813669,49,C,20,NaN,N,220,Burglary/Breaking & Entering,Property,Y,Y,5.0,Burglary/Breaking & Entering,A

In [116]:
coloradoIncidents = pd.read_csv('CO_2019_NIBRS_incident.csv')

In [117]:
coloradoOffenses = coloradoOffenses.merge(coloradoIncidents, how='left', on='INCIDENT_ID')

In [118]:
coloradoAgencies = pd.read_csv('CO_2019_agencies.csv')
coloradoAgencies

,YEARLY_AGENCY_ID,AGENCY_ID,DATA_YEAR,ORI,LEGACY_ORI,COVERED_BY_LEGACY_ORI,DIRECT_CONTRIBUTOR_FLAG,DORMANT_FLAG,DORMANT_YEAR,REPORTING_TYPE,UCR_AGENCY_NAME,NCIC_AGENCY_NAME,PUB_AGENCY_NAME,PUB_AGENCY_UNIT,AGENCY_STATUS,STATE_ID,STATE_NAME,STATE_ABBR,STATE_POSTAL_ABBR,DIVISION_CODE,DIVISION_NAME,REGION_CODE,REGION_NAME,REGION_DESC,AGENCY_TYPE_NAME,POPULATION,SUBMITTING_AGENCY_ID,SAI,SUBMITTING_AGENCY_NAME,SUBURBAN_AREA_FLAG,POPULATION_GROUP_ID,POPULATION_GROUP_CODE,POPULATION_GROUP_DESC,PARENT_POP_GROUP_CODE,PARENT_POP_GROUP_DESC,MIP_FLAG,POP_SORT_ORDER,SUMMARY_RAPE_DEF,PE_REPORTED_FLAG,MALE_OFFICER,MALE_CIVILIAN,PED.MALE_OFFICER+PED.MALE_CIVILIAN,FEMALE_OFFICER,FEMALE_CIVILIAN,PED.FEMALE_CIVILIAN+PED.FEMALE_OFFICER,0,0.1,NIBRS_CERT_DATE,NIBRS_START_DATE,NIBRS_LEOKA_START_DATE,NIBRS_CT_START_DATE,NIBRS_MULTI_BIAS_START_DATE,NIBRS_OFF_ETH_START_DATE,COVERED_FLAG,COUNTY_NAME,MSA_NAME,PUBLISHABLE_FLAG,PARTICIPATED,NIBRS_PARTICIPATED
0,18262019,1826,2019,CO0010000,CO0010000,NaN,N,N,NaN,I,ADAMS,ADAMS,Adams,NaN,A,7,Colorado,CO,CO,8,Mountain,4,West,Region IV,County,100624,23358,COUCR0001,Colorado Bureau of Investigation Uniform Crime...,Y,19,9A,"MSA counties 100,000 or over",9,MSA Counties,Y,3,R,Y,344,43,387,56,140,196,0,0,01-JAN-92,01-JAN-97,01-MAR-03,01-FEB-14,01-JAN-16,01-APR-13,N,ADAMS,"Denver-Aurora-Lakewood, CO",Y,Y,Y
1,18272019,1827,2019,CO0010100,CO0010100,NaN,N,N,NaN,I,AURORA,AURORA,Aurora,NaN,A,7,Colorado,CO,CO,8,Mountain,4,West,Region IV,City,380600,23358,COUCR0001,Colorado Bureau of Investigation Uniform Crime...,N,5,1C,"Cities from 250,000 thru 499,999",1,"All cities 250,000 or over",Y,1,R,Y,610,47,657,78,176,254,0,0,01-JAN-92,01-JAN-85,01-MAR-03,01-FEB-14,01-JAN-16,01-APR-13,N,DOUGLAS; ADAMS; ARAPAHOE,"Denver-Aurora-Lakewood, CO",Y,Y,Y
2,18282019,1828,2019,CO0010200,CO0010200,NaN,N,N,NaN,I,BRIGHTON,BRIGHTON,Brighton,NaN,A,7,Colorado,CO,CO,8,Mountain,4,West,Region IV,City,42267,23358,COUCR0001,Colorado Bureau of Investigation Uniform Crime...,Y,8,4,"Cities from 25,000 thru 49,999",4,"Cities from 25,000 thru 49,999",N,2,R,Y,59,5,64,16,21,37,0,0,01-JAN-92,01-SEP-04,01-JAN-06,01-FEB-14,01-JAN-16,01-APR-13,N,WELD; ADAMS,"Denver-Aurora-Lakewood, CO; Greeley, CO",Y,Y,Y
3,18292019,1829,2019,CO0010300,CO0010300,NaN,N,N,NaN,I,COMMERCE CITY,COMMERCE CITY,Commerce City,NaN,A,7,Colorado,CO,CO,8,Mountain,4,West,Region IV,City,60198,23358,COUCR0001,Colorado Bureau of Investigation Uniform Crime...,N,7,3,"Cities from 50,000 thru 99,999",3,"Cities from 50,000 thru 99,999",N,2,R,Y,93,6,99,17,20,37,0,0,01-JAN-92,01-JAN-97,01-MAR-03,01-FEB-14,01-JAN-16,01-APR-13,N,ADAMS,"Denver-Aurora-Lakewood, CO",Y,Y,Y
4,18302019,1830,2019,CO0010400,CO0010400,NaN,N,N,NaN,I,THORNTON,THORNTON,Thornton,NaN,A,7,Colorado,CO,CO,8,Mountain,4,West,Region IV,City,142168,23358,COUCR0001,Colorado Bureau of Investigation Uniform Crime...,N,6,2,"Cities from 100,000 thru 249,999",2,"Cities from 100,000 thru 249,999",Y,1,R,Y,206,6,212,36,71,107,0,0,01-JAN-92,01-JAN-12,01-SEP-12,01-JUL-14,01-FEB-16,01-APR-13,N,ADAMS,"Denver-Aurora-Lakewood, CO",Y,Y,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
216,232122019,23212,2019,CO0622400,CO0622400,NaN,N,N,NaN,I,HUDSON,HUDSON,Hudson,NaN,A,7,Colorado,CO,CO,8,Mountain,4,West,Region IV,City,1806,23358,COUCR0001,Colorado Bureau of Investigation Uniform Crime...,Y,11,7,"Cities under 2,500",7,"Cities under 2,500",N,2,R,Y,3,0,3,1,1,2,0,0,01-JAN-92,01-JAN-12,01-OCT-12,01-FEB-14,01-JAN-16,01-APR-13,N,WELD,"Greeley, CO",Y,Y,Y
217,232402019,23240,2019,CO0570300,CO0570300,NaN,N,N,NaN,I,MOUNTAIN VILLAGE,MOUNTAIN VILLAGE,Mountain Village,NaN,A,7,Colorado,CO,CO,8,Mountain,4,West,Region IV,City,1450,23358,COUCR0001,Colorado Bureau of Investigation Uniform Crime...,N,11,7,"Cities under 2,500",7,"Cities under 2,500",N,2,R,Y,6,2,8,1,1,2,0,0,01-JAN-92,01-FEB-13,01-JAN-13,01-MAR-14,01-FEB-16,01-APR-13,N,SAN MIGUEL,Non-MSA,Y,Y,Y
218,252672019,25267,2019,CO0418000,CO0418000,NaN,N,N,NaN,I,ALL CRIMES ENFORCEMENT T,ALL CRIMES ENFORCEMENT T,All Crimes Enforcement Team,NaN,A,7,Colorado,CO,CO,8,Mountain,4,West,Region IV,Other,0,23358,COUCR0001,Colorado Bureau of Investigation Uniform Crime...,N,11,7,"Cities under 2,500",7,"Cities under 2,500",N,2,R,Y,4,0,4,0,0,0,0,0,01-JAN-92,01-JAN-13,01-DEC-13,01-FEB-14,01-JAN-16,01-FEB-14,N,MOFFAT,Non-MSA,Y,Y,Y
219,253142019,25314,2019,CO0191000,CO0191000,NaN,N,N,NaN,I,GYPSUM,NaN,Gypsum,NaN,A,7,Colorado,CO,CO,8,Mountain,4,West,Region IV,City,7467,23358,COUCR0001,Colorado Bureau of Investigation Uniform Crime...,N,10,6,"Cities from 2,500 thru 9,999",6,"Cities from 2,500 thru 9,999",N,2,R,Y,4,0,4,0,0,0,0,0,01-JAN-92,01-FEB-14,01-FEB-14,01-FEB-14,01-JAN-16,01-FEB-14,N,EAGLE,Non-MSA,Y,Y,Y
220,290742019,29074,2019,CO030015Y,CO030015Y,NaN,N,N,NaN,I,DIV GAMING CRIM ENF INVEST SECTION,NaN,Division of Gaming Criminal Enforcement and In...,Golden,A,7,Colorado,CO,CO,8,Mountain,4,West,Region IV,Other State Agency,0,23358,COUCR0001,Colorado Bureau of Investigation Uniform Crime...,N,11,7,"Cities under 2,500",7,"Cities under 2,500",N,2,R,Y,11,13,24,3,19,22,0,0,01-JAN-92,01-JAN-19,01-JAN-19,NaN,NaN,NaN,N,JEFFERSON,"Denver-Aurora-Lakewood, CO",Y,Y,Y

In [119]:
coloradoOffenses = coloradoOffenses.merge(coloradoAgencies, how='left', on='AGENCY_ID')

In [120]:
denverOFFENSEcodes = pd.read_csv('DENVERoffense_codes.csv')

In [121]:
denverCrime = denverCrime.merge(denverOFFENSEcodes, on='OFFENSE_CODE',how='left')

In [122]:
denverCrime['REPORTED_DATE']=pd.to_datetime(denverCrime['REPORTED_DATE'])

In [123]:
import datetime 
start_date = "2019-1-1"
end_date = "2019-12-31"

after_start_date = denverCrime['REPORTED_DATE'] >= start_date
before_end_date = denverCrime['REPORTED_DATE'] <= end_date
between_two_dates = after_start_date & before_end_date
filtered_dates = denverCrime.loc[between_two_dates]

In [124]:
filtered_dates.sort_values('OFFENSE_ID')

,INCIDENT_ID,OFFENSE_ID,OFFENSE_CODE,OFFENSE_CODE_EXTENSION_x,OFFENSE_TYPE_ID_x,OFFENSE_CATEGORY_ID_x,FIRST_OCCURRENCE_DATE,LAST_OCCURRENCE_DATE,REPORTED_DATE,INCIDENT_ADDRESS,GEO_X,GEO_Y,GEO_LON,GEO_LAT,DISTRICT_ID,PRECINCT_ID,NEIGHBORHOOD_ID,IS_CRIME_x,IS_TRAFFIC_x,OFFENSE_CODE_EXTENSION_y,OFFENSE_TYPE_ID_y,OFFENSE_TYPE_NAME,OFFENSE_CATEGORY_ID_y,OFFENSE_CATEGORY_NAME,IS_CRIME_y,IS_TRAFFIC_y
925940,20196,20196521300,5213,0,weapon-unlawful-discharge-of,all-other-crimes,1/1/2019 12:02:00 AM,NaN,2019-01-01 00:57:00,1100 BLK N WILLOW ST,3172162.0,1692732.0,-104.887858,39.733761,2.0,223.0,east-colfax,1,0,0,weapon-unlawful-discharge-of,Unlawful discharge of a weapon,all-other-crimes,All Other Crimes,1,0
925941,20196,20196521300,5213,0,weapon-unlawful-discharge-of,all-other-crimes,1/1/2019 12:02:00 AM,NaN,2019-01-01 00:57:00,1100 BLK N WILLOW ST,3172162.0,1692732.0,-104.887858,39.733761,2.0,223.0,east-colfax,1,0,1,weapon-flourishing,Flourishing of a weapon,all-other-crimes,All Other Crimes,1,0
833446,201911,201911521300,5213,0,weapon-unlawful-discharge-of,all-other-crimes,12/31/2018 11:59:00 PM,NaN,2019-01-01 01:28:00,2800 BLK N HUMBOLDT ST,3149007.0,1701443.0,-104.970005,39.758073,2.0,211.0,whittier,1,0,1,weapon-flourishing,Flourishing of a weapon,all-other-crimes,All Other Crimes,1,0
833445,201911,201911521300,5213,0,weapon-unlawful-discharge-of,all-other-crimes,12/31/2018 11:59:00 PM,NaN,2019-01-01 01:28:00,2800 BLK N HUMBOLDT ST,3149007.0,1701443.0,-104.970005,39.758073,2.0,211.0,whittier,1,0,0,weapon-unlawful-discharge-of,Unlawful discharge of a weapon,all-other-crimes,All Other Crimes,1,0
385890,201960,201960520200,5202,0,weapon-carrying-concealed,all-other-crimes,1/1/2019 12:11:00 AM,NaN,2019-01-01 03:51:00,13691 E RANDOLPH PL,3188780.0,1716159.0,-104.828156,39.797748,5.0,521.0,montbello,1,0,0,weapon-carrying-concealed,Carrying a concealed weapon,all-other-crimes,All Other Crimes,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
699939,2019519190039,2019519190039531300,5313,0,curfew,public-disorder,5/19/2019 2:00:00 AM,NaN,2019-05-19 03:03:00,NaN,3131848.0,1689129.0,-105.031262,39.724528,4.0,411.0,barnum,1,0,0,curfew,Curfew,public-disorder,Public Disorder,1,0
1130683,2019659217111,2019659217111544400,5444,0,traf-habitual-offender,all-other-crimes,10/14/2019 11:27:00 PM,NaN,2019-10-15 00:54:00,W 4TH AVE / N PERRY ST,3129472.0,1688543.0,-105.039719,39.722953,4.0,411.0,barnum-west,1,0,0,traf-habitual-offender,Habitual traffic offender,all-other-crimes,All Other Crimes,1,0
890238,2019659217111,2019659217111549900,5499,0,traf-other,all-other-crimes,10/14/2019 11:27:00 PM,NaN,2019-10-15 00:54:00,W 4TH AVE / N PERRY ST,3129472.0,1688543.0,-105.039719,39.722953,4.0,411.0,barnum-west,1,0,0,traf-other,Traffic offense - other,all-other-crimes,All Other Crimes,1,0
890239,2019659217111,2019659217111549900,5499,0,traf-other,all-other-crimes,10/14/2019 11:27:00 PM,NaN,2019-10-15 00:54:00,W 4TH AVE / N PERRY ST,3129472.0,1688543.0,-105.039719,39.722953,4.0,411.0,barnum-west,1,0,1,vehicular-eluding,Vehicular eluding,all-other-crimes,All Other Crimes,1,0
890240,2019659217111,2019659217111549900,5499,0,traf-other,all-other-crimes,10/14/2019 11:27:00 PM,NaN,2019-10-15 00:54:00,W 4TH AVE / N PERRY ST,3129472.0,1688543.0,-105.039719,39.722953,4.0,411.0,barnum-west,1,0,2,vehicular-eluding-no-chase,Vehicular eluding - no chase,all-other-crimes,All Other Crimes,1,0

In [125]:
denverOFFENSEcounts = pd.DataFrame(filtered_dates['OFFENSE_CATEGORY_NAME'].value_counts()).reset_index()

In [126]:
pd.options.display.max_rows = 200
denverOFFENSEcounts['OFFENSE_CATEGORY_NAME'].sum()

224965

In [127]:
coloradoArrestees = pd.read_csv('CO_2019_NIBRS_ARRESTEE.csv')
coloradoArrestees

,DATA_YEAR,ARRESTEE_ID,INCIDENT_ID,ARRESTEE_SEQ_NUM,ARREST_DATE,ARREST_TYPE_ID,MULTIPLE_INDICATOR,OFFENSE_TYPE_ID,AGE_ID,AGE_NUM,SEX_CODE,RACE_ID,ETHNICITY_ID,RESIDENT_CODE,UNDER_18_DISPOSITION_CODE,CLEARANCE_IND,AGE_RANGE_LOW_NUM,AGE_RANGE_HIGH_NUM
0,2019,37454104,122137607,1,28-DEC-19,2,C,45,5,54,M,1,3,R,NaN,NaN,54,0
1,2019,37460105,122133856,1,30-DEC-19,2,C,35,5,28,M,1,2,R,NaN,NaN,28,0
2,2019,37454111,122137644,1,31-DEC-19,1,C,16,5,24,M,1,3,N,NaN,NaN,24,0
3,2019,37452104,122116889,2,27-MAR-19,3,M,44,5,59,M,1,3,R,NaN,NaN,59,0
4,2019,37452106,122116896,1,02-MAR-19,3,C,27,5,23,M,1,3,R,NaN,NaN,23,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90588,2019,35408700,116808837,1,12-SEP-19,2,C,47,5,14,F,1,1,R,R,NaN,14,0
90589,2019,35412888,116814208,1,18-AUG-19,3,C,45,5,38,F,1,2,U,NaN,NaN,38,0
90590,2019,35408862,116814220,1,16-AUG-19,3,C,16,5,33,M,1,2,R,NaN,NaN,33,0
90591,2019,35408865,116814229,1,23-SEP-19,2,C,51,5,52,M,1,3,N,NaN,NaN,52,0
90592,2019,35408867,116814237,1,30-AUG-19,3,C,51,5,24,F,1,2,N,NaN,NaN,24,0

In [128]:
coloradoOffenses = coloradoOffenses.merge(coloradoArrestees, how='left', on='INCIDENT_ID')

In [129]:
denverFBIoffenses = coloradoOffenses[coloradoOffenses['PUB_AGENCY_NAME']=='Denver']

In [130]:
FBIdenverOffensecounts = pd.DataFrame(denverFBIoffenses['OFFENSE_NAME'].value_counts()).reset_index()

In [131]:
FBIdenverOffensecounts['OFFENSE_NAME'].sum()

55577